### ISSUE TITLE
lib/charset.c:qp_encode() ensure that a multi-octet character is not split across adjacent 'encoded-word's

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2663] opened 2019-03-10 09:16 UTC
As required per RFC 2047 Section 5.

[PATCH v2](https://github.com/cyrusimap/cyrus-imapd/files/2949301/lib_charset_qp_encode.txt)

**Comment by rsto** [comment] 2019-03-11 10:29
I can't reproduce the issue described in the patch, but that's not to say there isn't an issue with the current implementation.

E.g. running your test input on my local build of the  master branch implementation of `charset_encode_mimeheader` returns:

    =?UTF-8?Q?=D0=94=D0=B8=D0=BB=D1=8F=D0=BD_=D0=9F=D0=B0=D0=BB=D0=B0=D1=83=D0=B7?=
    =?UTF-8?Q?=D0=BE=D0=B2?=

Note how it legally splits the encoded word only at valid UTF-8 boundaries. This is ensured by the ISUTF8CONTINUATION check. If the input wouldn't be a header, then splitting within UTF-8 words doesn't seem to be forbidden by RFC 2045.

What this issue shows is that the QP-encoder for headers can overrun the allowed line length. It should indeed split after the `=D1=83` sequence close to the end of the first line.

I'm working on fixing the line length issue, and your suggested solution looks reasonable. But if you found a way to produce illegal UTF-8 word splits in Q-encoded headers in the current implementation, please let me know.

**Comment by dilyanpalauzov** [comment] 2019-03-11 12:06
I discovered this with cyrus-3.0.

**Comment by dilyanpalauzov** [comment] 2019-03-11 12:41
The way the error was exposed was by uploading a meting with

ORGANIZER;CN=Дилян Палаузов…
ATTENDEE:mailto:x@different-host

Cyrus generated email/iMIP invitation with From: using as display-name the Common-Name converted to UTF-8-Q-encoding.  K9 had troubles displayimg the display name, as a single character was spread over two encoded-words.

**Comment by rsto** [comment] 2019-03-11 13:55
Thanks. @elliefm I've fixed this for the development branch, but the implementation on the 3.0 branch differs. Not sure how to handle this: backporting the fix shouldn't be much on an issue, or are going to pull in the latest charset library on 3.0 anyway?

The development branch fix is https://github.com/cyrusimap/cyrus-imapd/commit/3ca31fe0ee1ce3cdf71a062eae39b20b1ecb74d1

**Comment by dilyanpalauzov** [comment] 2019-03-11 15:04
The macro ISUTF8CONTINUATION is not used anymore and can be deleted.

**Comment by dilyanpalauzov** [comment] 2019-03-11 21:18
Looking at cunit/charser.testc:test_encode_mimeheader():

There is no difference, if one inserts in a header =?UTF-8?Q?abc? or abc, as at the end the same text is displayed.  Therefore the tests

TESTCASE("abc", "abc");
TESTCASE("abc\r\n", "=?UTF-8?Q?abc?=");

shall produce the same result – unencoded abc.

Likewise a test for "70times the letter A, space, some multi-octet characters” is missing.  The result shall be two lines, the first line being 70 times the letter A, without =?UTF-8?Q?…

I do not understand the purpose of feeding \r\n in charset_encode_mimeheader().  E.g. in

TESTCASE("abc\r\n xyz", "=?UTF-8?Q?abc?=\r\n =?UTF-8?Q?xyz?=");

depending on the purpose the space could be encoded as underscore.

**Comment by elliefm** [comment] 2019-03-12 01:22
@rsto Generally I don't plan to add new dependencies for 3.0.x releases.  So the way to go would be to backport just the fix to 3.0, rather than the whole new version.

I don't have a strong enough understanding of the charset handling to think about side effects/ramifications, but superficially at least, the fix looks sensible enough. :)

I'm planning to do a 3.0.9 release later this week (was meant to be late last week, but I got delayed).  How comfortable are you with the (backported) fix?  If you're happy that it's release quality, drop it onto the 3.0 branch ASAP and it'll get included.  Otherwise, sit on it until after the release, then it can percolate in git for a while.

**Comment by dilyanpalauzov** [comment] 2019-03-13 14:39
#2655 is unrelated.  Adding calender objects with attendee/organizer to a shared calender is not defined.

**Comment by elliefm** [comment] 2019-10-11 00:54
this was fixed in 3.0.9

**Closed by elliefm** 2019-10-11 00:54 UTC
Labels: 3.0, 3.1, bug
