### ISSUE TITLE
Cassandane failure Admin.imap_admins on all architectures

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2047] opened 2017-07-03 18:51 UTC
I'm now down to just two unexplained Cassandane failures.  They appear to be unrelated so I'll report them in separate tickets.

The Admin.imap_admins test fails consistently on all architectures.  It's not clear to me why this is; it looks to me that everything succeeds.  This is with Cyrus 3.0.2, and a Cassandane checkout from June 22.  But this failure has been constant since I started trying to run Cassandane as part of my package builds.

```
1) test_imap_admins(Cassandane::Cyrus::Admin)
 expected 'ok', got 'no' at Cassandane/Cyrus/Admin.pm line 90.
        Cassandane::Cyrus::Admin::test_imap_admins(Cassandane::Cyrus::Admin=HASH(0x559d9104c1b0)) called at /usr/share/perl5/vendor_perl/Test/Unit/TestCase.pm line 75
        [...framework calls elided...]

Annotations:
=====> Cyrus::TestCase[567] ---------- BEGIN test_imap_admins ----------
=====> Instance[1004] start main instance for test test_imap_admins: basedir /builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401
=====> Instance[455] Found binary cyr_buildinfo in /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin
=====> Instance[455] Found binary cyr_buildinfo in /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin
=====> Instance[1505] Running: "/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin/cyr_buildinfo" "-C" "/builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401/conf/imapd.conf"
=====> Instance[455] Found binary ctl_cyrusdb in /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin
=====> Instance[455] Found binary imapd in /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd
=====> Instance[916] started saslauthd for /builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401 as 18938
=====> Instance[1759] opening socket /builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401/run/mux
=====> Instance[943] started notifyd for /builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401 as 18939
=====> Instance[455] Found binary master in /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd
=====> Instance[1505] Running: "/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/master" "-C" "/builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401/conf/imapd.conf" "-l" "255" "-p" "/builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401/run/master.pid" "-d" "-M" "/builddir/build/BUILD/cyrus-imapd-3.0.2/cassandane/work/1845401/conf/cyrus.conf"
=====> Instance[868] _start_master: waiting for PID file
=====> Instance[871] _start_master: PID file present and correct
=====> Instance[883] _start_master: PID waiting for services
=====> Daemon[358] is_listening: service imap is listening on 127.0.0.1:9100
=====> Util::Wait[77] Waited 0.031621 sec for 127.0.0.1:9100 to be in LISTEN state
=====> Instance[894] _start_master: all services listening
=====> Instance[970] create user cassandane
=====> Util::Socket[63] create_client_socket INET host=127.0.0.1 port=9100
=====> Instance[1774] authdaemon connection: admin testpw imap
=====> Instance[1035] started main instance for test test_imap_admins: cyrus version 3.0.2-5.fc27 Fedora
=====> Cyrus::TestCase[574] Calling test function
=====> Util::Socket[63] create_client_socket INET host=127.0.0.1 port=9100
=====> Instance[1774] authdaemon connection: admin testpw imap
=====> Util::Socket[63] create_client_socket INET host=127.0.0.1 port=9100
=====> Instance[1774] authdaemon connection: imapadmin testpw imap
=====> Util::Socket[63] create_client_socket INET host=127.0.0.1 port=9100
=====> Instance[1774] authdaemon connection: cassandane testpw imap
=====> Cyrus::TestCase[681] Beginning tear_down
=====> Instance[1242] stop
=====> Instance[1204] _stop_pid: sending signal 15 to 18943
=====> Util::Wait[77] Waited 0.010139 sec for unknown condition
=====> Instance[919] killing saslauthd 18938
=====> Instance[946] killing notifyd 18939
=====> Instance[919] killing saslauthd 18938
=====> Cyrus::TestCase[726] ---------- END test_imap_admins ----------
=====> Daemon[387] checking for stray processes on ports: 9100
```

 This gets logged to syslog during that test:
```
1845401/master[18943]: process started
1845401/master[18945]: about to exec /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin/ctl_cyrusdb
1845401/ctl_cyrusdb[18945]: skiplist: clean shutdown file missing, updating recovery stamp
1845401/ctl_cyrusdb[18945]: SQL backend defaulting to engine 'pgsql'
1845401/ctl_cyrusdb[18945]: recovering cyrus databases
1845401/ctl_cyrusdb[18945]: done recovering cyrus databases
1845401/master[18943]: process type:START name:recover path:/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/sbin/ctl_cyrusdb age:0.000s pid:18945 exited normally
1845401/master[18943]: ready for work
1845401/master[18947]: about to exec /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd
1845401/imap[18947]: SQL backend defaulting to engine 'pgsql'
1845401/imap[18947]: executed
1845401/imap[18947]: accepted connection
1845401/imap[18947]: command: 1 Capability
1845401/imap[18947]: command: 2 Login
[127.0.0.1] admin plaintext User logged in SESSIONID=<1845401-18947-1499107540-1-16444475862873656246>
1845401/imap[18947]: command: 3 Create
1845401/imap[18947]: auditlog: create sessionid=<1845401-18947-1499107540-1-16444475862873656246> mailbox=<user.cassandane> uniqueid=<0d2cb4b0-20fb-44b7-a3a0-78565bca349e> uidvalidity=<1499107541>
1845401/imap[18947]: NOTIFY: response OK to method pusher
1845401/imap[18947]: command: 4 Setacl
1845401/imap[18947]: auditlog: acl sessionid=<1845401-18947-1499107540-1-16444475862873656246> mailbox=<user.cassandane> uniqueid=<0d2cb4b0-20fb-44b7-a3a0-78565bca349e> oldacl=<cassandane        lrswipkxtecdan        > acl=<cassandane        lrswipkxtecdan        admin        lrswipkxtecdan        >
1845401/imap[18947]: NOTIFY: response OK to method pusher
1845401/imap[18947]: auditlog: modseq sessionid=<1845401-18947-1499107540-1-16444475862873656246> mailbox=<user.cassandane> uniqueid=<0d2cb4b0-20fb-44b7-a3a0-78565bca349e> highestmodseq=<2>
1845401/imap[18947]: command: 5 Setacl
1845401/imap[18947]: NOTIFY: response OK to method pusher
1845401/imap[18947]: command: 6 Setacl
1845401/imap[18947]: auditlog: acl sessionid=<1845401-18947-1499107540-1-16444475862873656246> mailbox=<user.cassandane> uniqueid=<0d2cb4b0-20fb-44b7-a3a0-78565bca349e> oldacl=<cassandane        lrswipkxtecdan        admin        lrswipkxtecdan        > acl=<cassandane        lrswipkxtecdan        admin        lrswipkxtecdan        anyone        p        >
1845401/imap[18947]: NOTIFY: response OK to method pusher
1845401/imap[18947]: auditlog: modseq sessionid=<1845401-18947-1499107540-1-16444475862873656246> mailbox=<user.cassandane> uniqueid=<0d2cb4b0-20fb-44b7-a3a0-78565bca349e> highestmodseq=<3>
1845401/imap[18947]: command: 7 Logout
1845401/imap[18947]: USAGE admin user: 0.015689 sys: 0.006319
1845401/imap[18947]: auditlog: traffic sessionid=<1845401-18947-1499107540-1-16444475862873656246> bytes_in=<207> bytes_out=<1601>
1845401/imap[18947]: accepted connection
1845401/imap[18947]: command: 1 Capability
1845401/imap[18947]: command: 2 Login
[127.0.0.1] admin plaintext User logged in SESSIONID=<1845401-18947-1499107540-2-12137715576191804884>
1845401/master[18949]: about to exec /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd
1845401/imap[18949]: SQL backend defaulting to engine 'pgsql'
1845401/imap[18949]: executed
1845401/imap[18949]: accepted connection
1845401/imap[18949]: command: 1 Capability
1845401/imap[18949]: command: 2 Login
[127.0.0.1] imapadmin plaintext User logged in SESSIONID=<1845401-18949-1499107540-1-15923591968917596684>
1845401/master[18950]: about to exec /builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd
1845401/imap[18950]: SQL backend defaulting to engine 'pgsql'
1845401/imap[18950]: executed
1845401/imap[18950]: accepted connection
1845401/imap[18950]: command: 1 Capability
1845401/imap[18950]: command: 2 Login
[127.0.0.1] cassandane plaintext User logged in SESSIONID=<1845401-18950-1499107540-1-15742989835688099499>
1845401/imap[18947]: command: 3 Reconstruct
1845401/imap[18951]: Reconstructing 'user.cassandane' (not recursive) for user 'admin'
1845401/imap[18949]: command: 3 Logout
1845401/imap[18949]: USAGE imapadmin user: 0.008692 sys: 0.003244
1845401/imap[18949]: auditlog: traffic sessionid=<1845401-18949-1499107540-1-15923591968917596684> bytes_in=<52> bytes_out=<1537>
1845401/imap[18950]: command: 3 Logout
1845401/imap[18950]: USAGE cassandane user: 0.008632 sys: 0.003250
1845401/imap[18950]: auditlog: traffic sessionid=<1845401-18950-1499107540-1-15742989835688099499> bytes_in=<53> bytes_out=<1537>
1845401/imap[18947]: command: 4 Logout
1845401/imap[18947]: USAGE admin user: 0.000400 sys: 0.001226
1845401/imap[18947]: auditlog: traffic sessionid=<1845401-18947-1499107540-2-12137715576191804884> bytes_in=<79> bytes_out=<1566>
1845401/master[18943]: attempting clean shutdown on signal
1845401/imap[18950]: graceful shutdown
1845401/imap[18949]: graceful shutdown
1845401/imap[18947]: graceful shutdown
1845401/imap[18949]: auditlog: traffic sessionid=<1845401-18949-1499107540-1-15923591968917596684> bytes_in=<0> bytes_out=<0>
1845401/imap[18950]: auditlog: traffic sessionid=<1845401-18950-1499107540-1-15742989835688099499> bytes_in=<0> bytes_out=<0>
1845401/imap[18947]: auditlog: traffic sessionid=<1845401-18947-1499107540-2-12137715576191804884> bytes_in=<0> bytes_out=<0>
1845401/master[18943]: process type:SERVICE name:imap path:/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd age:0.066s pid:18949 exited, status 75
1845401/master[18943]: process type:SERVICE name:imap path:/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd age:0.053s pid:18950 exited, status 75
1845401/master[18943]: process type:SERVICE name:imap path:/builddir/build/BUILDROOT/cyrus-imapd-3.0.2-5.fc27.x86_64/usr/libexec/cyrus-imapd/imapd age:0.097s pid:18947 exited, status 75
1845401/master[18943]: All children have exited, closing down
```

**Comment by ajaysusarla** [comment] 2017-08-18 05:03
This potentially could be a permission issue. I've been able to run this test and it works consistently:
```
Cyrus::Admin.imap_admins                                                [  OK  ]
```
Is it possible to run the test with a `-vvv ` passed in? (`sudo -u cyrus ./testrunner.pl -vvv -f pretty -j 1 Admin.imap_admins`) Hopefully that will give us more information.

**Comment by jasontibbitts** [comment] 2018-06-01 21:40
I'm afraid that somehow I never saw your response.  Was just going over my test failures and realized I had filed this ticket but never checked back.

Adding -vvv doesn't really give anything useful, but running testrunner under strace makes it obvious:
```
23496 execve("/usr/sbin/reconstruct", ["/usr/sbin/reconstruct", "-C", "/builddir/build/BUILD/cyrus-imap"..., "user.cassandane"], 0x7ffd9e12daa8 /* 43 vars */) = -1 ENOENT (No such file or directory)
```

The problem is that this is running inside the Fedora buildsystem as part of a package build, and the software at that point has been installed with `make install DESTDIR=some_path`.  The only magic needed to make pretty much all of the rest of Cassandane work is just setting $LD_LIBRARY_PATH and $CYRUS_USER, and setting destdir properly in cassandane.ini.  But it appears that the location of reconstruct is hardcoded to be in SBIN_DIR.

There are three things which imapd will exec: cyr_expire, reconstruct and quota.  All are hardcoded to be in SBIN_DIR.

And, ouch, I just realized that quota especially is bad because, basically, you can't have an executable named "quota" in the path (since that's obviously already taken by the usual disk quota command). Fedora renames it to cyr_quota to avoid the conflict, but I realize now that I don't patch imap/imapd.c to actually call cyr_quota.  Oops.

In any case, I guess I'll file an RFE to handle this better.

**Comment by elliefm** [comment] 2018-06-04 03:11
Oooh that's a curly one

We can't detect a destdir setting at compile time, because it's an install-time override.  The "compile it as if it will be installed in /prefix, but actually install it to /destdir/prefix" behaviour is literally the whole point!  I imagine it would do the right thing if it was running chroot'd to /destdir, but that's a whole nother can of worms

Off the top of my head, I think the way to handle this would probably be to add optional imapd.conf settings to override the locations exec'd by imapd.  Ideally this would take the form of auditing all the things that get exec'd and doing something for all of them (vs tackling them piecemeal and winding up with a mess).  There'd be security aspects to take into consideration as well, I guess

**Comment by elliefm** [comment] 2018-06-04 03:33
Closing this one off, since we know the cause and have an RFE open for the solution :)

**Closed by elliefm** 2018-06-04 03:33 UTC
