### ISSUE TITLE
3.6.3 compiles, 3.8.1 fails due "optimization level attribute mismatch"

### ISSUE THREAD

**Issue by pieska** [cyrusimap/cyrus-imapd#4648] opened 2023-09-11 11:36 UTC
3.6.3 compiles fine, but 3.8.1 fails on the same system with

```
Making all in perl/imap
make[2]: Entering directory '/build/cyrus-imapd/src/cyrus-imapd-3.8.1/perl/imap'
Makefile:373: warning: ignoring prerequisites on suffix rule definition
Makefile:373: warning: ignoring prerequisites on suffix rule definition
cp IMAP/Admin.pm blib/lib/Cyrus/IMAP/Admin.pm
cp IMAP/Shell.pm blib/lib/Cyrus/IMAP/Shell.pm
cp IMAP.pm blib/lib/Cyrus/IMAP.pm
Running Mkbootstrap for IMAP ()
chmod 644 "IMAP.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- IMAP.bs blib/arch/auto/Cyrus/IMAP/IMAP.bs 644
"/usr/bin/perl" "/usr/share/perl5/core_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/core_perl/ExtUtils/typemap' -typemap '/build/cyrus-imapd/src/cyrus-imapd-3.8.1/perl/imap/typemap'  IMAP.xs > IMAP.xsc && mv IMAP.xsc IMAP.c
cc -c  -I../.. -I../../com_err/et    -I../../perl/imap -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/perl/src=/usr/src/debug/perl -flto=auto   -DVERSION=\"1.00\" -DXS_VERSION=\"1.00\" -fPIC "-I/usr/lib/perl5/5.38/core_perl/CORE"  -DPERL_POLLUTE IMAP.c
In file included from ../../lib/util.h:49,
                 from ../../lib/imapurl.h:45,
                 from IMAP.xs:55:
../../config.h:690: warning: "VERSION" redefined
  690 | #define VERSION "3.8.1"
      | 
<command-line>: note: this is the location of the previous definition
rm -f blib/arch/auto/Cyrus/IMAP/IMAP.so
LD_RUN_PATH="/usr/lib" cc   -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -fstack-protector-strong  IMAP.o  -o blib/arch/auto/Cyrus/IMAP/IMAP.so ../../perl/.libs/libcyrus.a ../../perl/.libs/libcyrus_min.a \
   -lsasl2 -lssl -lcrypto -lssl -lcrypto -luuid -lz   \
  
../../lib/util.c: In function ‘XS_Cyrus__IMAP_toURL’:
../../lib/util.c:1193:24: error: inlining failed in call to ‘always_inline’ ‘buf_len.localalias’: optimization level attribute mismatch
 1193 | EXPORTED inline size_t buf_len(const struct buf *buf)
      |                        ^
IMAP.xs:729:13: note: called from here
  729 |         if(!buf_len(&buf)) {
      |             ^
../../lib/util.c:1193:24: error: inlining failed in call to ‘always_inline’ ‘buf_len.localalias’: optimization level attribute mismatch
 1193 | EXPORTED inline size_t buf_len(const struct buf *buf)
      |                        ^
IMAP.xs:729:13: note: called from here
  729 |         if(!buf_len(&buf)) {
      |             ^
make[3]: *** [/tmp/ccD6Heye.mk:2: /tmp/ccKyRWXb.ltrans0.ltrans.o] Error 1
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:493: blib/arch/auto/Cyrus/IMAP/IMAP.so] Error 1
make[2]: Leaving directory '/build/cyrus-imapd/src/cyrus-imapd-3.8.1/perl/imap'
make[1]: *** [Makefile:7542: all-recursive] Error 1
make[1]: Leaving directory '/build/cyrus-imapd/src/cyrus-imapd-3.8.1'
make: *** [Makefile:3348: all] Error 2
```

Any Idea how to fix that?

**Comment by elliefm** [comment] 2023-09-13 00:13
Curious...

> `cc -c  [...] -O2 [...] IMAP.c`

Looks like it's compiling the XS module with `-O2`, but `buf_len()` in `../../lib/util.c` is declared like this:

```
EXPORTED inline size_t buf_len(const struct buf *buf)
    __attribute__((always_inline, optimize("-O3")));
```

And I guess it's complaining that `-O3` and `-O2` are not equal?  But I usually compile with `-O0`, and don't get any such complaints, even though zero is also not three.  When I look through my build logs, my builds compile IMAP.c with `-O2` like yours, so it looks like the perl XS build is always using `-O2`, overriding the `-O0` that I asked for... and yet it works for me, even though two is still not three.

What platform and compiler are you using, and what optimization level are you trying to use?

Presumably something has changed between 3.6 and 3.8 to cause this, but I've looked in a few likely places, and none of those places have changed since 3.2, so it must be somewhere I haven't looked yet.

**Comment by pieska** [comment] 2023-09-13 09:42
i'm building on archlinux with gcc 13.2.1. I noticed, the build is successful if i use makepkg, if i use extra-x86_64-build, which runs makepkg in a chroot, it fails. The difference is:

--- cyrus-imapd-3.8.1-1-x86_64-build.log.makepkg        2023-09-13 10:58:28.731371027 +0200
+++ cyrus-imapd-3.8.1-1-x86_64-build.log.extra  2023-09-13 11:03:41.239646017 +0200
@@ -611,157 +611,157 @@
 Build info:
    shared:             yes
    static:             no
-   cflags:             -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fno-toplevel-reorder
-   cxxflags:           -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS
+   cflags:             -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/cyrus-imapd/src=/usr/src/debug/cyrus-imapd -flto=auto -fno-toplevel-reorder
+   cxxflags:           -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/cyrus-imapd/src=/usr/src/debug/cyrus-imapd -flto=auto
    libs:                -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -lresolv -lresolv  -lresolv    -lz -lxml2  -lical -licalss -licalvcal   -lsqlite3
-   ldflags:            -Wl,-O1,--sort-common,-z,relro,-z,now
+   ldflags:            -Wl,-O1,--sort-common,-z,relro,-z,now -flto=auto
    libm:               -lm
    unit tests (cunit): 

The build fails in 3.8.1 if i use LTO (-flto=auto), 3.6.3 builds with LTO. if i disable LTO, 3.8.1 builds fine too.

**Comment by mosvald** [comment] 2023-09-13 14:03
Immediate fix for this:

~~~
$ cat patch-cyrus-remove-always-inline-for-buf-len
diff --git a/lib/util.c b/lib/util.c
index a2eae15..ef8c25b 100644
--- a/lib/util.c
+++ b/lib/util.c
@@ -1188,7 +1188,7 @@ EXPORTED int buf_getline(struct buf *buf, FILE *fp)
 
 #ifdef HAVE_DECLARE_OPTIMIZE
 EXPORTED inline size_t buf_len(const struct buf *buf)
-    __attribute__((always_inline, optimize("-O3")));
+    __attribute__((optimize("-O3")));
 #endif
 EXPORTED inline size_t buf_len(const struct buf *buf)
 {
$ 
~~~

I wanted to report this some time ago, but unfortunately, I got distracted by other work and it got postponed.

Detailed info can be found here:

https://bugzilla.redhat.com/show_bug.cgi?id=2223951#c8
https://bugzilla.redhat.com/show_bug.cgi?id=2223951#c10

**Comment by mosvald** [comment] 2023-09-13 14:22
> Presumably something has changed between 3.6 and 3.8 to cause this, but I've looked in a few likely places, and none of those places have changed since 3.2, so it must be somewhere I haven't looked yet.

https://github.com/cyrusimap/cyrus-imapd/commit/3e1ea54e4975acdcc5daa6fee60518a571a7f642

**Comment by elliefm** [comment] 2023-09-17 23:58
Oh I see, so the difference is not something we changed in or around `buf_len()` itself, but rather that IMAP.xs started to use `buf_len()` et al where previously it had not.  Hmm.

> `-flto=auto`

I'm reading the GCC docs for LTO, and it says (among other things) that source files should be compiled and linked with the same optimisation level.  We already noticed it compiling with `-O2` in the args, and looking again now I see it linking with `-Wl,-O1,[...]` instead, so that must be the "optimization level attribute mismatch" that it's complaining about.

I don't know much about Perl XS, but as far as I understand XS modules must be compiled and linked with the same compiler flags as perl itself, and we take some care to do so rather than just handing down the same compiler flags that Cyrus itself was built with.  So the `-O1` at link time is probably because that's how your perl was built, but for LTO purposes that makes it incompatible with libcyrus, built with `-O2`, or `buf_len()` with its `optimize("-O3")` attribute.

You might be able to make this work by recompiling perl with -O2 as well, but that's not a reasonable requirement -- most people don't and shouldn't need to build their own perl.  We probably ought to just assume perl's flags are not necessarily compatible with libcyrus's in the general case, and so I think Cyrus's XS modules should probably have `-fno-lto` added to LDFLAGS, so that the compiler even doesn't try to optimise across the XS/libcyrus boundary.

That said, I haven't managed to reproduce this locally.  I've tried adding `-flto=auto` to CFLAGS and LDFLAGS but they aren't getting passed down to the XS builds, I guess because we override them with perl's.  So `-flto=auto` being present at link time for you might imply that your perl was built with LTO, and that's why we're trying to use it for the XS modules too.  Hmm.

**Comment by elliefm** [comment] 2023-09-18 00:41
Ahh -- pasting the last comment from that RedHat Bugzilla report here for future reference:

> [Jakub Jelinek  2023-07-19 12:37:36 UTC](https://bugzilla.redhat.com/show_bug.cgi?id=2223951#c10)
> And the log quickly shows the reason.  IMAP.c (created from IMAP.xs) which calls buf_len is compiled with -fwrapv option, while lib/util.c is not.
> As whether operations on signed integers are wrapping or have undefined behavior or trapping aren't in GCC encoded in the IL, but come from per-function flags, it is really not possible to do such inlining.
> You can either drop the bogus always_inline, it doesn't help much, such trivial function is inlined whenever possible anyway, or compile
> IMAP.c without -flto=auto (or add -fno-lto), such that that TU which uses -fwrapv isn't LTO optimized together with the rest, etc.

That last point is the same solution I was thinking of...

The other possibility, dropping `always_inline` from `buf_len()`, I'm not so sure about.  It was added by d7b53694cdfd, whose commit message implies that profiling identified this as a hotspot worthy of imposing the additional optimisations on.  I agree this would most likely be inlined in optimised builds anyway, but I think the intent was to have these specific optimisations enabled even for `-O0` or `-Og` builds.

The original report talks about a difference between gcc 12.2.1 and 12.3.1 as being relevant too.  Since I'm still on gcc 10.2.1, I guess it's not really surprising that I can't reproduce this locally.

**Comment by elliefm** [comment] 2023-09-18 01:08
> [always_inline](https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-always_005finline-function-attribute)
> Generally, functions are not inlined unless optimization is specified. For functions declared inline, this attribute inlines the function independent of any restrictions that otherwise apply to inlining. Failure to inline such a function is diagnosed as an error. Note that if such a function is called indirectly the compiler may or may not inline it depending on optimization level and a failure to inline an indirect call may or may not be diagnosed.

Yeah, that's the behaviour we want here -- inline these specific functions if possible _even when compiled without optimisations_.

So I think the core problem is trying to perform LTO across incompatible translation units, so we should stop doing that, by adding `-fno-lto` to the XS build... somehow.

**Comment by elliefm** [comment] 2023-09-18 01:51
@pieska @mosvald:

Does a patch like this help?

```
diff --git a/perl/imap/Makefile.PL.in b/perl/imap/Makefile.PL.in
index 71416cc6a..3c8856f68 100644
--- a/perl/imap/Makefile.PL.in
+++ b/perl/imap/Makefile.PL.in
@@ -89,6 +89,7 @@ WriteMakefile(
                },
     'clean'    => {'FILES' => 'libcyrperl.a cyradm'},
     'LD'       => $Config{ld} . ' @GCOV_LDFLAGS@',
+    'LDDLFLAGS' => $Config{lddlflags} . ' -fno-lto',
     'OBJECT'    => 'IMAP.o',
     'MYEXTLIB'  => '@top_builddir@/perl/.libs/libcyrus.a @top_builddir@/perl/.libs/libcy>
     'LIBS'     => [ "$LIB_SASL @SSL_LIBS@ @LIB_UUID@ @ZLIB@ @GCOV_LIBS@ @LIBCAP_LIBS@"],
```

With this patch in place locally, I can see that `-fno-lto` is now passed through when linking IMAP.so:

```
[...]
rm -f blib/arch/auto/Cyrus/IMAP/IMAP.so
x86_64-linux-gnu-gcc   -shared -L/usr/local/lib -fstack-protector-strong -fno-lto  IMAP.o  -o blib/arch/auto/Cyrus/IMAP/IMAP.so ../../perl/.libs/libcyrus.a ../../perl/.libs/libcyrus_min.a \
   -lsasl2 -lssl -lcrypto -lssl -lcrypto -luuid -lz   \
  
chmod 755 blib/arch/auto/Cyrus/IMAP/IMAP.so
[...]
```

Though since I can't reproduce the failure, I can't confirm if this fixes it.

**Comment by pieska** [comment] 2023-09-18 18:56
```
Running Mkbootstrap for IMAP ()
chmod 644 "IMAP.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- IMAP.bs blib/arch/auto/Cyrus/IMAP/IMAP.bs 644
"/usr/bin/perl" "/usr/share/perl5/core_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/core_perl/ExtUtils/typemap' -typemap '/build/cyrus-imapd/src/cyrus-imapd-3.8.1/perl/imap/typemap'  IMAP.xs > IMAP.xsc && mv IMAP.xsc IMAP.c
cc -c  -I../.. -I../../com_err/et    -I../../perl/imap -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/perl/src=/usr/src/debug/perl -flto=auto   -DVERSION=\"1.00\" -DXS_VERSION=\"1.00\" -fPIC "-I/usr/lib/perl5/5.38/core_perl/CORE"  -DPERL_POLLUTE IMAP.c
In file included from ../../lib/util.h:49,
                 from ../../lib/imapurl.h:45,
                 from IMAP.xs:55:
../../config.h:690: warning: "VERSION" redefined
  690 | #define VERSION "3.8.1"
      | 
<command-line>: note: this is the location of the previous definition
rm -f blib/arch/auto/Cyrus/IMAP/IMAP.so
LD_RUN_PATH="/usr/lib" cc   -shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -fstack-protector-strong -fno-lto  IMAP.o  -o blib/arch/auto/Cyrus/IMAP/IMAP.so ../../perl/.libs/libcyrus.a ../../perl/.libs/libcyrus_min.a \
   -lsasl2 -lssl -lcrypto -lssl -lcrypto -luuid -lz   \
  
/usr/bin/ld: IMAP.o: plugin needed to handle lto object
/usr/bin/ld: IMAP.o: plugin needed to handle lto object
chmod 755 blib/arch/auto/Cyrus/IMAP/IMAP.so
```

although it complaints about lto objects the build succeeds.

**Comment by elliefm** [comment] 2023-09-19 23:56
Curious.  I guess that's an informational message rather than an error, otherwise surely it would have failed.  It might be telling you that you'll need some runtime plugin in order to actually use the IMAP.so that you've built?  There must be some way we can test the compiled library, and find out whether it actually works, but I'm not sure off the top of my head what that will be.  I'll poke around and see what I can figure out.

I see a lot of search results for "plugin needed to handle lto object", but none so far have been especially informative about what it means or its consequences, and a lot of the responses to people's questions have been along the lines of "add `-fno-lto`", but that's what we _did_.

**Comment by elliefm** [comment] 2023-09-20 00:27
After the build succeeds, what happens if you run `make -C perl/imap test`?

It fails for me for unrelated reasons ("IMAP.so: undefined symbol: pcreposix_regexec") but I'm not yet sure if that's something I've done wrong in my environment, or if it's broken in some other way too...

**Comment by elliefm** [comment] 2023-09-20 04:01
I think my "undefined symbol" problem is something to do with those tests using the IMAP.so from the build directory, and missing some hook that would be present if properly installed.  If I actually install the built cyrus, and then run the installed `cyradm` (which ends up loading IMAP.so), it seems to work fine.  It would be nice if these tests could actually work, but I think that's a different issue for a different day.  

In the meantime, does `cyradm` work for you once built with the `-fno-lto` patch and installed?

If it fails with something like `Can't locate Cyrus/IMAP/Shell.pm in @INC`, that's a separate problem, which might be fixed by a patch like this:

```
diff --git a/tools/fixsearchpath.pl b/tools/fixsearchpath.pl
index ca7c40698..be82a9b50 100755
--- a/tools/fixsearchpath.pl
+++ b/tools/fixsearchpath.pl
@@ -82,7 +82,9 @@ BEGIN {
         my $d = $0;
 EOT
 ;
-$boilerplate .= "       my \$bindir = " . quote($configure_bindir) . ";\n";
+$boilerplate .= "        my \$bindir = "
+    .  quote($configure_prefix . $configure_bindir)
+    . ";\n";
 $boilerplate .= << 'EOT'
         # remove the filename, $d is now the installed bindir
         $d =~ s/\/[^\/]+$//;
```

If `cyradm` works (possibly with that extra patch), then I think that tells us that the `-fno-lto` patch is working fine, despite the "plugin needed" message.  If it doesn't work, hopefully it gives us an error message that sheds some further light! :)

**Comment by pieska** [comment] 2023-09-20 15:50
cyradm does not work, IMAP.so is missing almost all symbols:

```
$ cyradm 
Can't find 'boot_Cyrus__IMAP' symbol in /usr/lib/perl5/5.38/site_perl/auto/Cyrus/IMAP/IMAP.so
 at /usr/lib/perl5/5.38/site_perl/Cyrus/IMAP/Admin.pm line 43.
Compilation failed in require at /usr/lib/perl5/5.38/site_perl/Cyrus/IMAP/Admin.pm line 43.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.38/site_perl/Cyrus/IMAP/Admin.pm line 43.
Compilation failed in require at /usr/lib/perl5/5.38/site_perl/Cyrus/IMAP/Shell.pm line 59.
BEGIN failed--compilation aborted at /usr/lib/perl5/5.38/site_perl/Cyrus/IMAP/Shell.pm line 59.
Compilation failed in require at /usr/bin/cyradm line 66.
BEGIN failed--compilation aborted at /usr/bin/cyradm line 66.

$ objdump -t /usr/lib/perl5/5.38/site_perl/auto/Cyrus/IMAP/IMAP.so

/usr/lib/perl5/5.38/site_perl/auto/Cyrus/IMAP/IMAP.so:     file format elf64-x86-64

SYMBOL TABLE:
0000000000000000 l    df *ABS*	0000000000000000 IMAP.c
0000000000000000 l    df *ABS*	0000000000000000 
0000000000003e58 l     O .dynamic	0000000000000000 _DYNAMIC
0000000000004008 l     O .data	0000000000000000 __TMC_END__
0000000000004000 l     O .data	0000000000000000 __dso_handle
0000000000001000 l     F .init	0000000000000000 _init
00000000000010ec l     F .fini	0000000000000000 _fini
0000000000003fc8 l     O .got	0000000000000000 _GLOBAL_OFFSET_TABLE_
0000000000000000  w      *UND*	0000000000000000 __cxa_finalize
0000000000000000  w      *UND*	0000000000000000 _ITM_registerTMCloneTable
0000000000004009 g     O .bss	0000000000000001 __gnu_lto_slim
0000000000000000  w      *UND*	0000000000000000 _ITM_deregisterTMCloneTable
0000000000000000  w      *UND*	0000000000000000 __gmon_start__
```

if you build the whole package completely without -flto it works, it also works if always_inline is removed.

**Comment by elliefm** [comment] 2023-09-22 00:32
Interesting, I wonder if this is related to that "plugin needed" message from earlier...

Most reports of that plugin needed message are reporting it as an error, but it hasn't been an error for IMAP.so.  But perhaps the lack of the required plugin is resulting in a nearly-empty IMAP.so, which would fail with an error later if we built anything else that linked against it.  But since we don't, it goes unnoticed until you try to run `cyradm`.

I'm not real clear on what the answer may be here, but here's some vaguely relevant links I've perused:

* https://bugzilla.redhat.com/show_bug.cgi?id=1857264
* https://bugzilla.redhat.com/show_bug.cgi?id=1467409
* https://gcc.gnu.org/wiki/LinkTimeOptimizationFAQ
* https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html

Some general points I'm getting:
* There may be a "liblto_plugin.so" on your system that needs to be placed in some standard location, and maybe isn't there by default
* Compiling with `-ffat-lto-objects` may remove the need for the plugin
* `ar`, `ranlib`, `nm` might need to be replaced with `gcc-ar`, `gcc-ranlib`, `gcc-nm`

I notice that for me, the `perl/imap/Makefile` that gets generated by the top-level configure contains `AR = ar` and `FULL_AR = /usr/bin/ar`.  These aren't passed down from above (though they could be).  My `config.log` also contains `AR='ar'` and `RANLIB='ranlib'`, so for me, it doesn't seem to matter that they weren't passed down.

What do you have for AR= and RANLIB= in your config.log?  If the top-level configure is detecting `gcc-ar` and `gcc-ranlib` for your system, then perhaps we just need to pass those details down to the perl builds.

For whatever it's worth, at Fastmail we build Cyrus without optimisations, other than the specific hotspots we've identified and added the optimise attributes to.  For the most part it's more likely to be IO-bound than CPU-bound, so extra optimisation isn't worth much, and would just make debugging harder.  It would be cool to get LTO working, but you won't be missing anything without it.  If you really want a measurable performance boost, use faster disks.

**Comment by pieska** [comment] 2023-09-25 14:58
gcc-ar and gcc-ranlib are available but not detected and used, the build is using standard ar and ranlib:

$ grep '^AR\|^RANLIB' config.log 
AR='ar'
RANLIB='ranlib'

I think, the build documentation should just mention that lto should not be used. On fedora 38 lto is standard and a note about the issue would be helpful for those using distros with lto as default.

**Comment by elliefm** [comment] 2023-09-26 23:25
Yeah, good thinking, I'll put something together.

**Closed** 2023-10-10 22:29 UTC
