### ISSUE TITLE
Cyrus cannot unlink/remove duplicated mails from/in multiple mailboxes

### ISSUE THREAD

**Issue by nuddelaug** [cyrusimap/cyrus-imapd#3126] opened 2020-07-27 09:48 UTC
### Your platform, and if applicable, your distribution and the distribution version.

Red Hat Enterprise 7.8 

### The exact version of Cyrus IMAP or SASL you are using.

cyrus-imap-2.4.17-15.el7.x86_64.rpm

### If a packaged version is used, the source of the packaged version.

cyrus-imapd-2.4.17-15.el7.src.rpm

### If relevant, are you using altnamespace, unixhierarchysep, or virtdomains?

/etc/imapd.conf
configdirectory: /var/lib/imap
partition-default: /var/spool/imap
admins: cyrus 
sievedir: /var/lib/imap/sieve
sendmail: /usr/sbin/sendmail
hashimapspool: true
sasl_pwcheck_method: saslauthd
sasl_mech_list: PLAIN
tls_cert_file: /etc/pki/cyrus-imapd/cyrus-imapd.pem
tls_key_file: /etc/pki/cyrus-imapd/cyrus-imapd.pem
tls_ca_file: /etc/pki/tls/certs/ca-bundle.crt
\# uncomment this if you're operating in a DSCP environment (RFC-4594)
\# qosmarking: af13
allowplaintext: yes
duplicatesuppression: 0

\# duplicatesuppression is disable by default on RHEL systems and would grant us to resend mandatory messages through SMTP server spool restores.

### What did you do?

keep running in disk full conditions even though all mailboxes have quota assigned.

### What did you expect to happen, and what actually happened?

Reason seems to be that messages delivered to multiple mailboxes do not get _cleaned_ when all of them expunged the mails.
For example: (these mailboxes are utilized for automatic processing of data)

A mail with data for being processed by dev-tst-ops (Pipeline) is delivered to three individual Mailboxes (user.mail1, user.mail2, user.mail3)
The automatic processing is connected through again three individual Accounts on IMAPS, read their mailbox and delete&expunge their mails within a few seconds (periodic runs on established connections)

Cyrus after receiving the message through LMTP stores the message and links it against the other mailboxes

$ find . -inum 19809465 -exec grep Message-ID {} \;
Message-ID: <1595795419_2863@ws03-rn09>
Message-ID: <1595795419_2863@ws03-rn09>
Message-ID: <1595795419_2863@ws03-rn09>

$ find . -inum 19809465 -exec stat {}  \;  | egrep -e '(Inode|Size|Access)' 
  Size: 66158     	Blocks: 136        IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 19809465    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-26 20:31:35.776243680 +0000
  Size: 66158     	Blocks: 136        IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 19809465    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-26 20:31:35.776243680 +0000
  Size: 66158     	Blocks: 136        IO Block: 4096   regular file
Device: fd03h/64771d	Inode: 19809465    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-26 20:31:35.776243680 +0000

even though the mailboxes are empty and quota/usage report _no space used_ the files stay in the file systems and _block_ space

$ /usr/lib/cyrus-imapd/mbexamine user.mail1 user.mail2 user.mail3| egrep -e '(Path|Unique ID|Number|Seq)' 
  Path to mailbox: /var/spool/imap/n/user/mail1
  Unique ID: 3aa873bc5f1da3f8
  Generation Number: 0
  Number of Messages: 0  Mailbox Size: 0 bytes
  Highest Mod Sequence: 13861

  Path to mailbox: /var/spool/imap/m/user/mail2
  Unique ID: 553c7a4c5f1da478
  Generation Number: 0
  Number of Messages: 0  Mailbox Size: 0 bytes
  Highest Mod Sequence: 12349

  Path to mailbox: /var/spool/imap/m/user/mail3
  Unique ID: 554be9945f1da169
  Generation Number: 0
  Number of Messages: 0  Mailbox Size: 0 bytes
  Highest Mod Sequence: 12421

\# du -hsx m/user/mail1 m/user/mail2 m/user/mail3
363M	m/user/mail1
53M	        m/user/mail2
5.1M	m/user/mail3

**Comment by elliefm** [comment] 2020-07-29 05:48
Thanks for the very thorough issue report!

A couple of further questions:

* Have you run `cyr_expire`?  Usually (in current versions), cleaning up expunged messages from disk is handled by `cyr_expire`, which should be run regularly (either from cron or the cyrus.conf EVENTS section) to take care of this.  I think you want the `-X <days>` option in this case, but I'm not especially familiar with 2.4 -- please check your cyr_expire man page for details.  If running `cyr_expire` with some option cleans up the old files, you'll need to arrange for this to run regularly.
* If you're already running cyr_expire regularly, whether from cron or cyrus.conf, can you please show the invocations that are being run?
* What's your imapd.conf value for "expunge_mode"?  It's not included in the snippet you provided, but it's not clear to me whether the snippet is the whole file, or just part of it.  If you do not have "expunge_mode" defined in your imapd.conf, please let me know that too.

Thanks :)

**Comment by nuddelaug** [comment] 2020-07-29 07:25
@elliefm,

yes we tried cyr_expire as well unfortunately nothing happens there as well
```
$ /usr/lib/cyrus-imapd/cyr_expire -D10m -E10m -X10m -a -v
Expunging deleted messages in mailboxes older than 0.01 days

Expunged 0 out of 76039 messages from 33 mailboxes

$ /usr/lib/cyrus-imapd/cyr_expire -D1 -E1 -X1 -a -v
Expunging deleted messages in mailboxes older than 1.00 days

Expunged 0 out of 74207 messages from 33 mailboxes
```

currently the most promising _workaround_ seems to be finding mailbox files with multiple links and remove them after a certain period of access (hoping that really all of them are already processed) 

```
$ find /var/spool/imap -links 3 -cmin +60 -type f -exec rm -f {} \;
```

**Comment by nuddelaug** [comment] 2020-07-29 16:31
@elliefm,

how to reproduce ... 

* create a small cyrus server 
* create three mailboxes
* send an identical mail to all three mailboxes
* login with one account and delete the message
* verify that the file is still in the file system


``` 
>>> s = imaplib.IMAP4('172.17.0.19')
>>> s.login('user1', 'changeme')
('OK', ['[CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxte QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SORT SORT=MODSEQ SORT=DISPLAY THREAD=ORDEREDSUBJECT THREAD=REFERENCES ANNOTATEMORE LIST-EXTENDED WITHIN QRESYNC SCAN XLIST URLAUTH URLAUTH=BINARY X-NETSCAPE LOGINDISABLED COMPRESS=DEFLATE IDLE] User logged in SESSIONID=<4aa463e0f5ce-248-1596039948-1>'])
>>> s.select('INBOX')
('OK', ['1'])
>>> s.store(1, '+FLAGS', '\\Deleted')
('OK', ['1 (FLAGS (\\Recent \\Deleted))'])
>>> s.expunge()
('OK', ['1'])
>>> s.select('INBOX')
('OK', ['0'])
```

```
[root@4aa463e0f5ce imap]# stat u/user/user1/1. u/user/user2/1. u/user/user3/1. 
  File: 'u/user/user1/1.'
  Size: 313       	Blocks: 8          IO Block: 4096   regular file
Device: fd1ch/64796d	Inode: 18890763    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-29 16:24:59.000000000 +0000
Modify: 2020-07-29 16:24:59.000000000 +0000
Change: 2020-07-29 16:24:59.328913220 +0000
 Birth: -
  File: 'u/user/user2/1.'
  Size: 313       	Blocks: 8          IO Block: 4096   regular file
Device: fd1ch/64796d	Inode: 18890763    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-29 16:24:59.000000000 +0000
Modify: 2020-07-29 16:24:59.000000000 +0000
Change: 2020-07-29 16:24:59.328913220 +0000
 Birth: -
  File: 'u/user/user3/1.'
  Size: 313       	Blocks: 8          IO Block: 4096   regular file
Device: fd1ch/64796d	Inode: 18890763    Links: 3
Access: (0600/-rw-------)  Uid: (   76/   cyrus)   Gid: (   12/    mail)
Access: 2020-07-29 16:24:59.000000000 +0000
Modify: 2020-07-29 16:24:59.000000000 +0000
Change: 2020-07-29 16:24:59.328913220 +0000
 Birth: -
```

```
[root@4aa463e0f5ce imap]# /usr/lib/cyrus-imapd/mbexamine user.user1
Examining user.user1...
 Mailbox Header Info:
  Path to mailbox: /var/spool/imap/u/user/user1
  Mailbox ACL: user1	lrswipkxtecda	cyrus	lrswipkxtecda	
  Unique ID: 244320575f21a1ab
  User Flags: [none]

 Index Header Info:
  Generation Number: 0
  Minor Version: 12
  Header Size: 128 bytes  Record Size: 96 bytes
  Number of Messages: 0  Mailbox Size: 0 bytes
  Last Append Date: (1596039899) Wed Jul 29 16:24:59 2020
  UIDValidity: 1596039595  Last UID: 1
  Deleted: 0  Answered: 0  Flagged: 0
  Mailbox Options: POP3_NEW_UIDL
  Last POP3 Login: (0) Thu Jan  1 00:00:00 1970
  Highest Mod Sequence: 5

 Message Info:
[root@4aa463e0f5ce imap]# /usr/lib/cyrus-imapd/mbexamine user.user1
Examining user.user1...
 Mailbox Header Info:
  Path to mailbox: /var/spool/imap/u/user/user1
  Mailbox ACL: user1	lrswipkxtecda	cyrus	lrswipkxtecda	
  Unique ID: 244320575f21a1ab
  User Flags: [none]

 Index Header Info:
  Generation Number: 0
  Minor Version: 12
  Header Size: 128 bytes  Record Size: 96 bytes
  Number of Messages: 0  Mailbox Size: 0 bytes
  Last Append Date: (1596039899) Wed Jul 29 16:24:59 2020
  UIDValidity: 1596039595  Last UID: 1
  Deleted: 0  Answered: 0  Flagged: 0
  Mailbox Options: POP3_NEW_UIDL
  Last POP3 Login: (0) Thu Jan  1 00:00:00 1970
  Highest Mod Sequence: 5

 Message Info:
```

**Comment by nuddelaug** [comment] 2020-07-29 18:20
@elliefm,

the key factor that these files are not deleted when expunged is that the connection is still open and reused. When I manually kill the client connection, the files are purged from disk as expected.

**Comment by brong** [comment] 2020-07-30 03:46
Ahh yeah, this is "expected" for 2.4 (we changed the locking behaviour in 2.5+ for this case).

You don't need to kill the connection, just unselect the mailbox to release the lock.

Obviously we're not going to backport the changed locking behaviour to 2.4!

**Comment by brong** [comment] 2020-07-30 03:47
I have removed "needs tests" because it's a waste of time to create a test for a known behaviour of a version which is no longer being updated.

**Comment by nuddelaug** [comment] 2020-07-30 04:28
Guys @brong @elliefm ,

thanks very much for you support on that. I think you can close the issue completley as I will try to get Red Hat add a more recent version to their release that supports long lasting connections.

**Comment by elliefm** [comment] 2020-07-31 01:12
From brong's comment, "You don't need to kill the connection, just unselect the mailbox to release the lock.", it sounds like you won't necessarily need an update from RedHat for this to work (though, running a version that's supported upstream isn't a bad idea either!)

> The automatic processing is connected through again three individual Accounts on IMAPS, read their mailbox and delete&expunge their mails within a few seconds (periodic runs on established connections)

Like, it sounds to me like you have some custom tooling that watches these mailboxes for mail?  And it sounds like, once connected, it just sits in a loop like:

1) fetch new mail
2) process, delete, and expunge new messages
3) goto 1

If you're able to modify the scripts (or whatever they are), this could probably be changed to something like

1) select INBOX
2) fetch new mail
3) process, delete, and expunge new messages
4) unselect INBOX
5) goto 1

The unselect will drop the mailbox lock for a moment, which means when cyr_expire runs it will be able to slide in that window and clean up the expunged stuff.

**Comment by rjbs** [comment] 2024-11-26 15:12
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.

**Closed by rjbs** 2024-11-26 15:12 UTC
Labels: 2.4
