### ISSUE TITLE
JMAP Calendar date range query can't search before 1970

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2379] opened 2018-05-29 00:15 UTC
POST /jmap/ HTTP/1.1
Host: 10.202.71.80:2073
Content-Type: application/json
User-Agent: Net-JMAPTalk/0.10
Authorization: Basic ...                                                 
Accept: application/json
Content-Length: 177

{"methodCalls":[["CalendarEvent/query",{"filter":{"after":"1949-06-20T00:00:00Z","before":"1968-10-14T00:00:00Z"},"accountId":"brong@brong.net"},"0"]],"using":["ietf:jmapmail"]}>1527552671>HTTP/1.1 500 Internal Server Error
Date: Tue, 29 May 2018 00:11:11 GMT
Vary: Accept-Encoding
Content-Type: text/html; charset=utf-8
Content-Length: 477

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>500 Internal Server Error</title>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>Unknown code ____ 251</p>
    <hr>
    <address>Cyrus-HTTP/3.1.3-630-gc623347-future Cyrus-SASL/2.1.26 LibXML2.9.1 OpenSSL/1.0.0 Zlib/1.2.8 SQLite/3.8.7.1 LibiCal/3.0 ICU4C/61.1 Jansson/2.11 Server at 10.202.71.80 Port 2073</address>
  </body>
</html>

**Comment by rsto** [comment] 2018-05-29 12:42
I couldn't reproduce that 500 Server error.

I could however find a issue in calendar queries which didn't accept ISO 8601 date-times. I've pushed a fix to master here https://github.com/cyrusimap/cyrus-imapd/commit/5cfffaaed989ce2880b980cec312dfd2247f4b68 and there's a Cassandane test that uses the exact query-range from this issue report here https://github.com/cyrusimap/cassandane/commit/30c7ec4a9dd740b423cfd741f2f556e49a5f0c09

Could you please cherry-pick that commit and see if there's still a crasher?

**Comment by rsto** [comment] 2018-05-30 08:57
Fixed with 5cfffaaed989ce2880b980cec312dfd2247f4b68 and ba20087092f3acde12d5d48a90e16425df29979a

**Closed by rsto** 2018-05-30 08:57 UTC
Labels: jmap
