### ISSUE TITLE
Building fails with "imap/http_err.h: No such file or directory"

### ISSUE THREAD

**Issue by HGuillemet** [cyrusimap/cyrus-imapd#2823] opened 2019-07-03 08:50 UTC
Compilation of master fails with error:

```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.   -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H           -fPIC  -fvisibility=hidden -g -O2 -MT imap/libcyrus_imap_la-http_client.lo -MD -MP -MF imap/.deps/libcyrus_imap_la-http_client.Tpo -c -o imap/libcyrus_imap_la-http_client.lo `test -f 'imap/http_client.c' || echo './'`imap/http_client.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/local/libexec\" -DSBIN_DIR=\"/usr/local/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -fPIC -fvisibility=hidden -g -O2 -MT imap/libcyrus_imap_la-http_client.lo -MD -MP -MF imap/.deps/libcyrus_imap_la-http_client.Tpo -c imap/http_client.c  -fPIC -DPIC -o imap/.libs/libcyrus_imap_la-http_client.o
imap/http_client.c:57:10: fatal error: imap/http_err.h: No such file or directory
 #include "imap/http_err.h"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

config.log: [config.log](https://github.com/cyrusimap/cyrus-imapd/files/3354082/config.log).

Please note that the platform is gentoo, and the system does install release 3.0.10 successfully from source.

**Comment by dilyanpalauzov** [comment] 2019-07-03 11:39
configure.log contains:
```
configure:24954: checking for com_err in -lcom_err
configure:24979: gcc -o conftest -g -O2   conftest.c -lcom_err     -lpcre -lpcreposix -lz >&5
configure:24979: $? = 0
configure:24988: result: yes
configure:24996: checking et/com_err.h usability
configure:24996: gcc -c -g -O2  conftest.c >&5
configure:24996: $? = 0
configure:24996: result: yes
configure:24996: checking et/com_err.h presence
configure:24996: gcc -E  conftest.c
configure:24996: $? = 0
configure:24996: result: yes
configure:24996: checking for et/com_err.h
configure:24996: result: yes
configure:25015: checking for compile_et
configure:25033: found /usr/bin/compile_et
configure:25046: result: /usr/bin/compile_et
```
which means, that the bundled compile_et is not built.

When you type `make` without any targets, it tries to generate imap/imap_err.c by calling `/usr/bin/compile_et imap/imap_err.et …/imap/imap_err.c` (once for the .c file, and once for the .h file).  On your system this has not worked somehow.  With `make V=1` you can see what precisely is executed to generate that file.

**Comment by HGuillemet** [comment] 2019-07-04 08:30
`make V=1 ` shows `compile_et` lines for `imap_err`, `mupdate_err`, `nntp_err`, `lmtp_err`, `sieve_err` but not `http_err`

**Comment by dilyanpalauzov** [comment] 2019-07-04 09:13
`make` creates imap/http_err.c, when building `httpd` is requested.  Your build fails in imap/http_client.c, which is built unconditionally: even when httpd is not created.

This has been raised at https://github.com/cyrusimap/cyrus-imapd/issues/2754 .

**Comment by dilyanpalauzov** [comment] 2019-07-04 09:24
Note, that changing this, requires blessing from FastMail and it is unpredictable whether somebody from FastMail will look at this within reasonable time, whatever conditions are satisfied.

**Comment by elliefm** [comment] 2019-07-10 08:23
Confirming this is a duplicate of #2754.  Continuing discussion/investigation over there since there's already some progress on that one, so I'm closing this one.  Thanks for providing the config.log!

**Closed by elliefm** 2019-07-10 08:23 UTC
