### ISSUE TITLE
ptscache_db_path config option does not work correctly

### ISSUE THREAD

**Issue by liutaurasa** [cyrusimap/cyrus-imapd#2625] opened 2019-01-08 16:21 UTC
In cyrus-imapd 2.5.11 I try to set 
`ptscache_db_path: /var/tmp/cyrus-imapd/ptscache.db`
in /etc/imapd.conf, however ptloader tries to fetch cache records from the database which is located in <configdir>/ptclient/ptscache.db . I can see that because:
`IOERROR: stating /srv/imap/config/ptclient/ptscache.db: No such file or directory
 ptload(): error fetching record: cyrusdb error(did ptloader add the record?)
ptload completely failed: unable to canonify identifier: cyrus-admin`

Liutauras

**Comment by elliefm** [comment] 2019-01-14 01:18
Confirmed -- looks like ptloader, ptexpire and ptdump all ignore the ptscache_db_path setting, but auth_pts honours it.  Not fixed in any of the newer versions yet either

**Closed** 2019-01-14 04:42 UTC
Labels: 2.5, 3.0, 3.1

**Comment by elliefm** [comment] 2019-01-14 05:02
The fix for 2.5 is here: 1a30a31e7463a9490d9dd85a5da0d6c744487d63

If you want, you can download that as an ordinary patch file by appending ".patch" to the url, like this: https://github.com/cyrusimap/cyrus-imapd/commit/1a30a31e7463a9490d9dd85a5da0d6c744487d63.patch
