### ISSUE TITLE
Build without http (and without libical) fails with undefined reference to `extract_icalbuf'

### ISSUE THREAD

**Issue by anatoli26** [cyrusimap/cyrus-imapd#3142] opened 2020-08-14 13:23 UTC
@elliefm,

When trying to build cyrus without http, i.e.

```
./configure --disable-http
```

I get multiple errors like:

```
imap/.libs/libcyrus_imap.so: undefined reference to `extract_icalbuf'
```

I see the code that references this function is mostly wrapped with `#ifdef USE_HTTPD`, nevertheless there is one instance where it's not: `imap/index.c line 5789`.

Then, there's a number of unconditional calls to `ical_support_init()`. Does that mean that libical is an unconditional mandatory dependency? We specified on the Compiling page that it's only needed for CalDAV.

**Comment by elliefm** [comment] 2020-08-17 00:28
> Does that mean that libical is an unconditional mandatory dependency?

I can't remember off the top of my head, but maybe we're moving in this direction.  Or maybe it's just a mistake, and simply needs compilation guards.  To clarify, are you talking about 3.2 or the master branch?

`ical_support_init()` (and therefore libical, I suppose) are needed for anything that needs timezone awareness.  I think maybe the scope of features that are timezone-aware has grown over time, and may no longer be limited to just the DAV features?

**Comment by anatoli26** [comment] 2020-08-21 08:11
> I think maybe the scope of features that are timezone-aware has grown over time, and may no longer be limited to just the DAV features?

Can we confirm this somehow? Just a yes or no. If it's a _yes_, then I'd change the docs. If it's a _no_, then the guards would have to be placed around these calls (I could also do this).

**Comment by anatoli26** [comment] 2020-08-21 08:14
> To clarify, are you talking about 3.2 or the master branch?

I was trying to build 3.2.2 on Ubuntu 16.04 for a test and it requires ical 3.0 which is not available in 16.04 (I know it's an old version), so I decided to disable everything using ical lib (according to the Compiling page), but found it's not enough.

**Comment by elliefm** [comment] 2020-08-24 00:07
I think on 3.2 we just need to fix the missing compilation guards.

For master, I'm not yet -- I'll check on our next conf call whether we expect or plan for libical to be mandatory or not, and that'll determine how to move forward there.

**Comment by elliefm** [comment] 2020-08-24 03:47
> I get multiple errors like:
> 
> ```
> imap/.libs/libcyrus_imap.so: undefined reference to `extract_icalbuf'
> ```
> 
> I see the code that references this function is mostly wrapped with `#ifdef USE_HTTPD`, nevertheless there is one instance where it's not: `imap/index.c line 5789`.

Okay this is quite confusing.  On current 3.2, and also in 3.2.2 specifically, all the calls to `extract_icalbuf` are already protected behind `#ifdef USE_HTTPD`?  There is no call to it on line 5789.

I checked master, and there is one such unprotected call, but it is at line 5721, not 5789.  (I'll look at this one specifically later, once I've confirmed the status of the libical dependency.)

> Then, there's a number of unconditional calls to ical_support_init(). Does that mean that libical is an unconditional mandatory dependency? We specified on the Compiling page that it's only needed for CalDAV.

The only calls to this function in 3.2 are from httpd.c and dav_reconstruct.c, neither of which are built when `--disable-http` is configured.  On master, there's one more call, from lmtpd.c (for sieve snooze -- not http-related).  This is currently unprotected, and we'll need to figure out what we want to do about it in order to figure out how to protect it properly, so I'll bring this detail up when we discuss the rest too.

I can't currently see anything on 3.2 that needs fixing... though it's hard to completely remove libical from my system to confirm that for certain, since I have it installed from cyruslibs rather than a package manager.

**Comment by rsto** [comment] 2020-08-24 07:51
> I checked master, and there is one such unprotected call, but it is at line 5721, not 5789. (I'll look at this one specifically later, once I've confirmed the status of the libical dependency.)

This call to extract_icalbuf should be handled the same as the one a couple of lines earlier. They do the same thing if the MIME parts are either TEXT/CALENDAR or APPLICATION/ICS.

**Comment by anatoli26** [comment] 2020-08-24 12:27
> I checked master, and there is one such unprotected call, but it is at line 5721, not 5789. (I'll look at this one specifically later, once I've confirmed the status of the libical dependency.)

Sorry, this was actually on a local branch based on a bit outdated master. Made a number of different tests and got that mixed.

Just re-checked everything again and the 3.2.2 tag has no issues with libical; only master has them: the 2 unprotected calls to `extract_icalbuf` and `ical_support_init` that you mentioned.

**Comment by ksmurchison** [comment] 2020-08-24 14:06
This is fixed in master with the following commits:

https://github.com/cyrusimap/cyrus-imapd/commit/e7adf30347af48d3715f7710fbee23244f151526
https://github.com/cyrusimap/cyrus-imapd/commit/2a54d6e8acc78e6a7d1e69be197297199cb45dfa
https://github.com/cyrusimap/cyrus-imapd/commit/46cc32b2f862296768cadd77934398bb720bf1be

**Closed by ksmurchison** 2020-08-24 14:06 UTC
