### ISSUE TITLE
Annotations: internal interfaces, make them go through their modseq-sources

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1859] opened 2017-03-08 13:29 UTC
At the moment, there's a generic interface for setting scope for an annotations database object, which then allows you to update the database, but it reduces clarity around database opening, and creates locking inversions because you then need to go BACK to the mailbox struct that's already open to update modseq information.

It would make more sense for all per-message annotations to happen purely through mailbox.c, for all per-mailbox annotations and server annotations to still happen through their regular codepath, but to not have all the database handling magic, just have a global annotations.db again like mboxlist.c has for mailboxes.

**Comment by rsto** [comment] 2019-05-21 12:14
Duplicate of #1860

**Closed by rsto** 2019-05-21 12:14 UTC
