### ISSUE TITLE
Email/set bulk operations

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2467] opened 2018-08-02 04:10 UTC
At the moment Email/set#update iterates over each ID to update in turn.  This is woefully inefficient for the "delete 1000 emails" usecase, where a bunch of messages are being moved.  The IMAP equivalent "MOVE 1:1000 Trash" is obviously massively more efficient.

The Email/set#update and Email/set#delete cases are the two highest priorities for optimisation within the Cyrus JMAP code.  I expect the answer is to collect the actions into a group and then 
perform them as a single transaction (possibly by creating a append_copy action from them)

**Comment by rsto** [comment] 2018-08-02 07:43
I'm going to tackle Email/set#delete  first. What are the typical usage patterns for bulk Email/set#update? Keyword updates? Mailbox moves? Or isn't there a pattern we can optimize for?

**Comment by elliefm** [comment] 2018-08-02 07:57
cynical guess: "i accidentally moved my entire inbox to trash" (ten minutes later) "i moved my entire trash back to inbox"

**Comment by rsto** [comment] 2018-08-02 08:04
Well, I guess that's why we delay expunging messages from Trash :)

But if mailbox moves are the thing to optimize for, that would actually be good news: it's the keyword/flag updates in Email/set#update that are brittle.

**Comment by robmueller** [comment] 2018-08-02 10:16
I observed this problem yesterday. I happened to have 5,000 postmaster emails in my Inbox I didn't want. I used an appropriate search to find them and then tried to delete them. Normally in the AJAX UI that takes a few seconds. It took several minutes in the JMAP UI.

Now the JMAP UI does send actions in batches to the server (so it can show a progress bar and cancel button), so I can handle it being a bit slower, but 50x slower isn't really acceptable.

I presume what's happening at the moment is something like:

- Iterate over all the emailIds, for each emailId:
  - Lookup the corresponding (folder, uid)
  - Open the mailbox
  - Action the uid
  - Close the mailbox

The problem there is lots of opening and closing mailboxes. At least, I *hope* this is what the problem is, because then the solution is fairly straight forward:

- Iterate over all the emailIds, for each emailId:
  - lookup the corresponding (folder, uid)
  - Build a map of folder -> [ ... list of uids ... ]
- Iterater over all folders in the map, for each folder:
  - Open the mailbox
  - Actioning the list of uids in one go
  - Close the mailbox

**Comment by rsto** [comment] 2018-08-02 10:40
Thanks. Yes, this is about what we'll do for set#destroy. The more we can narrow down the same issue for set#update, e.g. with exemplary requests, the more we can optimize them. E.g. I guess that a special-case worth optimizing is Email/set#update where the mailboxIds property just contains a single mailbox (e.g. Trash)?

**Comment by robmueller** [comment] 2018-08-02 10:53
It appears the UI currently does this when moving to a folder (e.g. Archive or Trash).
```
update | {…}
  M60090e772a17c717fbe3bf3d | {…}
    mailboxIds/0ad75de34850a900 | true
    mailboxIds/7ca07c9844751b4f | null
```
This when permanently deleting an email:
```
destroy | […]
  0 | M4eb22c6c79908ef3f2c7674b
```
This when marking an email read:
```
update | {…}
  Mcbc173320a71d12c13324154 | {…}
    keywords/$seen | true
```
When you archive an unread email:
```
update | {…}
  M42e85c22c036d97df60838ba | {…}
    keywords/$seen | true
    mailboxIds/0ad75de34850a900 | true
    mailboxIds/7ca07c9844751b4f | null
```
Hopefully all these cases at least can be optimised quite well.

**Comment by rsto** [comment] 2018-08-02 10:56
Thanks for this. It's interesting that the UI seems to prefer to null out the existing mailboxIds with a PatchObject, rather than just setting the mailboxIds property to a new value with a single mailboxId.

**Comment by robmueller** [comment] 2018-08-02 11:00
I presume this is an internal design decision based around "Archive" = "Remove from Inbox, add to Archive folder, leave anywhere other folder it's in untouched", so it acts more like labels from a user perspective.

**Comment by robmueller** [comment] 2018-08-02 11:01
And not just "Archive" but really any move operation is "remove label of current folder, add label of new folder" as a better description of the action, even if internally in cyrus, this actually means moving it between real folders.

**Comment by rsto** [comment] 2018-08-02 14:36
This is implemented now for Email/set#destroy: https://github.com/cyrusimap/cyrus-imapd/commit/a238ab4a2e10510e3bab182977c12b06c22dc9ef

I'll work on Email/set#update next.

**Comment by rsto** [comment] 2018-08-20 07:10
Email/set#update is implemented since https://github.com/cyrusimap/cyrus-imapd/commit/3e2c2f9d39c06aeab5502c3c6d9ad7e396381b87 with a couple of bug fixes since then.

**Closed by rsto** 2018-08-20 07:10 UTC
Labels: jmap
