### ISSUE TITLE
Xapian search fails because conversations db isn't filled during replication

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#2376] opened 2018-05-28 10:13 UTC
I noticed with version 3.0.6 that regular searches worked where fuzzy searches did not:

```
C SEARCH BODY "Jahren"
* SEARCH 20 77 211 224 255 264 331 351 368 383 404 436 438 439 484 551 568 596 738 754 757 760 761 773 780 810 840 850 892 918 939 946 973 991 1000 1005 1042 1094 1105 1118 1119 1151 1159 1223 1272 1280 1299 1311 1318 1337 1349 1352 1366 1375 1378 1385 1417 1422 1423 1431 1436 1445 1446 1459 1460 1465 1469 1475 1476 1481 1485 1489 1490 1493 1494 1501 1503 1510 1514 1524 1551 1557 1559 1561 1567 1573 1575 1577 1578 1607 1611 1614 1621 1622 1624 1629 1633 1637 1638 1643 1647 1648 1649 1653 1673 1676 1677 1682 1683 1686 1687 1688 1706 1708 1711 1712 1715 1721 1722 1724 1725 1726 1731 1735 1748 1749 1753 1756 1759 1760 1761 1762 1766 1779 1780 1803 1805 1806 1807 1809 1810 1812 1903 1904
C OK Completed (144 msgs in 0.650 secs)
D SEARCH FUZZY BODY "Jahren"
* SEARCH
D OK Completed (0 msgs in 0.000 secs)
```

Consequently, when using version 3.0.7 plus the patch for the new search_fuzzy_always option, and with that option enabled, all searches seem to fail:

```
B search body "jahr"
* SEARCH
B OK Completed (0 msgs in 0.000 secs)
```

It's quite possible that my setup is broken, but I don't see it. I tried stepping through the search process in gdb, but I'm not familiar enough with the code to notice what is going wrong.

**Comment by elliefm** [comment] 2018-05-28 11:00
The SearchFuzzy Cassandane tests pass for 3.0, so my guess is that this will be a setup problem. But I don't have any hunches what might be missing.

**Comment by rsto** [comment] 2018-05-28 11:32
There's a couple of directions we can take this to identify why it's not working for you:

-  Cassandane: do you have a working Cassandane setup? If so, do the SearchFuzzy test suite tests run OK on your machine?
- Stemming: To reduce the possible root causes, it would help to first check if the issue shows up for English text as well. Most probably your issue is not related to internationlisation, but if you could test searching for some English words, that would help.
- Looking into the Xapian databases: it would be interesting to see what's actually stored in your Xapian databases. The `xapian-delve` binary (possibly with a version suffix like `-1.5`) allows to inspect Xapian databases. E.g. to see all terms indexed in a Xapian db spool file, I'd do 

      # /usr/local/cyruslibs/bin/xapian-delve-1.5 -a 1131250101/search/c/user/cassandane/xapian/
      All terms in database: XBcom XBtest XBuser [...]

  What's showing up in your Xapian databases?

**Comment by hagedose** [comment] 2018-05-28 11:43
Cassandane: I tried getting it to work previously. I wasn't really successful, because my builds disable many features.

Stemming: this search does not work either:

```
. search body "translation"
* SEARCH
. OK Completed (0 msgs in 0.000 secs)

```

I played around with xapian-delve before, but not on this user's index. The output of this command looks fine:

` xapian-delve -a /var/spool/imapsearch/S/user/a101891/xapian.145`

All the terms I tried to search for appear.

**Comment by hagedose** [comment] 2018-05-28 11:44
Is there a specific breakpoint I could set in gdb? What should I be looking for?

**Comment by rsto** [comment] 2018-05-28 11:58
The relevant code is a bit all over the codebase, but I'd  start looking at `imap/xapian-wrap.cpp:xapian_query_run`.

If this function gets call, you'll know if Xapian is used at all for this query, and if so, what's the query? you can inspect the C string representation of the query with `query->get_description().c_str()`.

Also, within the for loop you'll get a cyrusid for each message that matches that query. This string gets passed as a C string to the callback, which looks up the message by Cyrus-internal guid. The callback in this case will be `imap/search_xapian.c:xapian_run_cb`.

Deep-diving into this part of the code will require some time, but if you have a gdb at hand, you'd be good to at least identify if Xapian returns anything at all. If so, there's something in Cyrus that's breaking for you.

**Comment by hagedose** [comment] 2018-05-28 12:18
Hm, the function gets called, but I'm not able to inspect the expression:

```
(gdb) inspect query->get_description().c_str()
Attempt to take address of value not located in memory.

```
The for loop iterates multiple times. The callback gets called:

Breakpoint 2, xapian_run_cb (cyrusid=0xea5db8 "*G*41d5e096996af3a164ae801e67c6cb59e557ef81", rock=rock@entry=0xf67a00)
    at imap/search_xapian.c:926

So at first glance it looks like the Xapian part is doing its job, right?

**Comment by rsto** [comment] 2018-05-28 12:35
Yes, that looks OK and there's something broken in your setup/the Cyrus codebase after that point. Just as a thought: You do have conversations enabled in the config, right? Cyrus should complain loudly if you are using Xapian without conversations, but who knows, we might have missed some checks...

**Comment by hagedose** [comment] 2018-05-28 12:38
Yes, conversations are enabled. Please let me know if you think of other things I could check.

**Comment by rsto** [comment] 2018-05-28 12:44
I'm afraid you'll have to `gdb` your way through `xapian_run_cb` in `imap/search_xapian.c`. Is the search callback in line 1204 (`1204         r = bb->proc(mboxname, uidvalidity, uid, bb->rock);` called? 

We need to find out where Cyrus comes to the conclusion that there is no message UID matching that GUID that we got from Xapian. A GUID should match to one ore more stored messages (identified by mailboxname:UID), and conversations.db is used in this codepath to do the mapping from GUID to UIDs.

**Comment by hagedose** [comment] 2018-05-28 15:03
The line  `r = bb->proc(mboxname, uidvalidity, uid, bb->rock);` has number 968 in my copy of `imap/search_xapian.c` and is never called. The server doesn't have legacy cyrusids, so that block is never executed. More later ...

**Comment by hagedose** [comment] 2018-05-28 15:26
My best guess is that 
```
myforeach (db=0xfa7120, prefix=0x10d2fe0 "G910964d5ab3db5311c6a0b2c061ed10d41544609", prefixlen=41, goodp=0x0,
    cb=0x7fd5429c8190 <_guid_cb>, rock=0x7fff56cdb5d0, tidptr=<optimized out>) at lib/cyrusdb_skiplist.c:1119
```

does not find a message matching the ID in the conversations db. I wonder if that file is damaged.

```
$ file /var/lib/imap/user/S/a101891.conversations
/var/lib/imap/user/S/a101891.conversations: Cyrus skiplist DB
$ /usr/lib/cyrus-imapd/cyr_dbtool dump skiplist /var/lib/imap/user/S/a101891.conversations

Sorry, you cannot use this tool with relative path names.
This is because some database backends (mainly berkeley) do not
always do what you would expect with them.

Please use absolute pathnames instead.
```

That doesn't seem right?!

**Comment by elliefm** [comment] 2018-05-29 01:56
I'm just in the middle of another train of thought so I can't do this just now, but what I'll do later (if no-one beats me to it) is look through the Cassandane tests and see what that environment sets up, because that'll show us everything it needs to work. :)

**Comment by elliefm** [comment] 2018-05-29 01:58
> Cassandane: I tried getting it to work previously. I wasn't really successful, because my builds disable many features.

You'll be pleased to know I'm working on making Cassandane more resilient to disabled Cyrus features (i.e. skipping tests for features that aren't compiled in).  If you want to open an issue on the Cassandane repo with your ./configure command, I can target your setup specifically, instead of just tackling it piecemeal  :)

**Comment by elliefm** [comment] 2018-05-30 02:05
These seem to be all the imapd.conf settings that Cassandane's SearchFuzzy suite specifically sets up:

```
search_engine => 'xapian',
search_index_headers => 'no',
search_batchsize => '8192',
defaultsearchtier => 't1',
't1searchpartition-default' => "$self->{basedir}/search",
conversations => 'on'
```

And there doesn't seem to be any search-related settings in the general defaults that every test suite runs with.  So it looks to me like your setup is fine.

I saw from your `cyr_buildinfo` output in the other issue that your xapian_flavor is vanilla.  I'm not familiar with exactly how much difference that makes, but maybe there's a clue there for @rsto

**Comment by elliefm** [comment] 2018-06-01 03:01
The Xapian audit tool in #2375 might be useful here, I think I'm gonna backport it to 3.0.

**Comment by rsto** [comment] 2018-07-23 12:39
Is still an issue?

**Comment by hagedose** [comment] 2018-07-23 13:02
Yes, but I haven't had time to look at it for the past two months. I might find some time to spare next month.

**Comment by rsto** [comment] 2018-07-24 07:08
Thanks for the update. I'll unassign myself to keep it off my working backlog then. Feel free to ping on this issue or the cyrus-devel list if you are ready.

**Comment by hagedose** [comment] 2018-08-15 13:00
@rsto Today my colleague and I figured out that the conversations file for that user was basically empty. After running "ctl_conversationsdb -z" and "ctl_conversationsdb -b" the search appears to be working now.
We will perform more tests on other user's mailboxes and either update this issue or create a new one. I'll leave this one open for now.

**Comment by hagedose** [comment] 2018-08-15 13:46
OK, so here is what's happening. We're planning on upgrading from a server running 2.4 by syncing. That's what I've been testing. I just tried from scratch with a user named a102382. On the server running 2.4:

```
sync_client -v -u a102382
USER a102382
```

In the log on the server running 3.0.8 I see this:

```
Aug 15 15:36:00 cyrus/squatter[2344]: indexing mailbox user/a102382...
Aug 15 15:36:02  cyrus/squatter[2344]: Xapian committed 1102 updates in 0.400249 sec

```
But the conversationsdb is empty:

```
ctl_conversationsdb -v -d a102382
$COUNTED_FLAGS
Fuser.a102382	0 (572 0 0)
```

Is that expected behavior?

**Comment by brong** [comment] 2019-02-11 10:35
This appears fixable :)

https://github.com/cyrusimap/cyrus-imapd/commit/15e56257e02d0b7e13bf9dc44224d55e8f3e3015

This will be in the next 3.0 release.

Bron.

**Closed by brong** 2019-02-11 10:35 UTC
