### ISSUE TITLE
Message text for cyr_virusscan should be controllable

### ISSUE THREAD

**Issue by postilion** [cyrusimap/cyrus-imapd#2516] opened 2018-09-11 14:14 UTC
The current message template for reporting viruses, in cyr_virusscan, is hard coded in append_notifications().  This should be controllable by the admin, to allow for local site preference, or language needs.

**Comment by jh1995** [comment] 2019-05-31 13:04
Duplicate of https://github.com/cyrusimap/cyrus-imapd/issues/1845 ? Anyway, this enhancement is needed.

**Closed** 2019-09-09 00:13 UTC
Labels: 3.0, 3.1

**Comment by elliefm** [comment] 2019-09-09 01:13
This is probably easy to backport to 3.0 but it's not really tested enough to be shipping as a stable feature.

If you'd like a 3.0 backport of this to test and provide feedback on, @ me and I'll rebase a branch for you.  Otherwise, it'll be master-only until 3.2 ships :)
