### ISSUE TITLE
Set virtdomains to userid as default, instead of off.

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#2082] opened 2017-08-09 00:30 UTC
From #2081 

> This is a minor "problem"... just found it:
> 
> The Chapter "Updates to default configuration" from  
> https://www.cyrusimap.org/imap/download/release-notes/3.0/x/3.0.0.html  
> say:
> 
>    "virtdomains is now userid by default (was off)
> 
> Indeed virtdomains is still "off" by default.

Make a change in the next release to make virtdomains set to `userid` by default, and updating release notes/upgrade guide to suit.

**Comment by nicolan** [comment] 2017-08-09 00:31
@elliefm I gave this to you because while I can tweak lib/imapoptions myself, I wasn't sure what else might need fiddling to make this work properly and you understand the release/upgrade implications better.

**Comment by nicolan** [comment] 2017-08-23 07:10
Reassigning. @ksmurchison can you make this happen for the 3.1 line? It'll need documentation in release notes and upgrade information too.

**Comment by ksmurchison** [comment] 2017-08-23 11:57
@nicolan  Do you want me to add the docs or hand back to you after I make the imapoptions change?

**Comment by elliefm** [comment] 2019-10-11 02:41
closing this as a duplicate of #2847 (even though this one predates it)

**Closed by elliefm** 2019-10-11 02:41 UTC
Labels: 3.1
