### ISSUE TITLE
3.0.6 fails Cassandane's Caldav::supports_event test

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2332] opened 2018-04-30 17:43 UTC
While updating the Fedora packages for 3.0.6 I found that, with no changes other than updating to 3.0.5 and dropping the upstreamed patches, Cassandane's Caldav::supports_event test now fails.  Which is odd as that test only creates a calendar with Net::CalDAVTalk and tests to see if it has the _can_event property.

The underlying caldav version hasn't changed; I'm building both 3.0.5 and 3.0.6 with an identical set of dependencies.  I don't see anything about calendar events in the release notes, and I looked through all of the commits since 3.0.5 and didn't see anything that stood out.  Is it possible that this is tied in with JMAP support somehow?

The complete test output follows. Sorry for the length, but I figured I should include it even thought the reason for the failure is fairly obvious.
```
Test Results:
Run: 731, Failures: 1, Errors: 0
There was 1 failure:
1) test_supports_event(Cassandane::Cyrus::Caldav)
 Boolean assertion failed at /usr/share/perl5/vendor_perl/Test/Unit/Exception.pm line 13.
        Test::Unit::Exception::throw_new(Test::Unit::Failure=HASH(0x55e52b261950), "-package", "Cassandane::Cyrus::Caldav", "-file", "Cassandane/Cyrus/Caldav.pm", "-line", 2890, "-object", ...) called at /usr/share/perl5/vendor_perl/Test/Unit/Assert.pm line 85
        Test::Unit::Assert::do_assertion(Cassandane::Cyrus::Caldav=HASH(0x55e528cb9320), Test::Unit::Assertion::Boolean=REF(0x55e52b2571a8), "Cassandane::Cyrus::Caldav", "Cassandane/Cyrus/Caldav.pm", 2890) called at /usr/share/perl5/vendor_perl/Test/Unit/Assert.pm line 19
        Test::Unit::Assert::assert(Cassandane::Cyrus::Caldav=HASH(0x55e528cb9320), JSON::PP::Boolean=SCALAR(0x55e526b2d030)) called at Cassandane/Cyrus/Caldav.pm line 2890
        Cassandane::Cyrus::Caldav::test_supports_event(Cassandane::Cyrus::Caldav=HASH(0x55e528cb9320)) called at /usr/share/perl5/vendor_perl/Test/Unit/TestCase.pm line 75
        [...framework calls elided...]
Annotations:
=====> Cyrus::TestCase[565] ---------- BEGIN test_supports_event ----------
=====> Instance[1074] start main instance for test test_supports_event: basedir /builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405
=====> Instance[1057] started smtpd as 12325
=====> Instance[473] Found binary cyr_buildinfo in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/sbin
=====> Instance[473] Found binary cyr_buildinfo in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/sbin
=====> Instance[1593] Running: "/builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/sbin/cyr_buildinfo" "-C" "/builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/conf/imapd.conf"
2018/04/30-12:02:56 Cassandane::Net::SMTPServer (type Net::Server::PreForkSimple) starting! pid(12325)
Resolved [localhost]:19169 to [::1]:19169, IPv6
Resolved [localhost]:19169 to [127.0.0.1]:19169, IPv4
Binding to TCP port 19169 on host ::1 with IPv6
Binding to TCP port 19169 on host 127.0.0.1 with IPv4
Group Not Defined.  Defaulting to EGID '135 135'
User Not Defined.  Defaulting to EUID '7225'
=====> Instance[473] Found binary ctl_cyrusdb in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/sbin
=====> Instance[473] Found binary httpd in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/libexec/cyrus-imapd
=====> Instance[473] Found binary imapd in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/libexec/cyrus-imapd
=====> Instance[945] started saslauthd for /builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405 as 12339
=====> Instance[1856] opening socket /builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/run/mux
=====> Instance[972] started notifyd for /builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405 as 12341
=====> Instance[888] _start_master: logging to /builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/conf/master.log
=====> Instance[473] Found binary master in /builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/libexec/cyrus-imapd
=====> Instance[1593] Running: "/builddir/build/BUILDROOT/cyrus-imapd-3.0.6-1.fc29.x86_64/usr/libexec/cyrus-imapd/master" "-C" "/builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/conf/imapd.conf" "-l" "255" "-p" "/builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/run/master.pid" "-d" "-M" "/builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/conf/cyrus.conf" "-L" "/builddir/build/BUILD/cyrus-imapd-3.0.6/cassandane/work/1702540405/conf/master.log"
=====> Instance[897] _start_master: waiting for PID file
=====> Instance[900] _start_master: PID file present and correct
=====> Instance[912] _start_master: PID waiting for services
=====> Daemon[356] is_listening: service http is listening on 127.0.0.1:19170
=====> Util::Wait[75] Waited 0.037463 sec for 127.0.0.1:19170 to be in LISTEN state
=====> Daemon[356] is_listening: service imap is listening on 127.0.0.1:19171
=====> Instance[923] _start_master: all services listening
=====> Instance[999] create user cassandane
=====> Util::Socket[61] create_client_socket INET host=127.0.0.1 port=19171
C: 1 capability
S: * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE AUTH=PLAIN AUTH=LOGIN SASL-IR] epithumnia.math.uh.edu Cyrus IMAP 3.0.6-1.fc29 Fedora server ready
S: * CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION URLAUTH URLAUTH=BINARY AUTH=PLAIN AUTH=LOGIN SASL-IR COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE
S: 1 OK Completed
C: 2 login admin "testpw"
=====> Instance[1871] authdaemon connection: admin testpw imap 
S: 2 OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE ACL RIGHTS=kxten QUOTA MAILBOX-REFERRALS NAMESPACE UIDPLUS NO_ATOMIC_RENAME UNSELECT CHILDREN MULTIAPPEND BINARY CATENATE CONDSTORE ESEARCH SEARCH=FUZZY SORT SORT=MODSEQ SORT=DISPLAY SORT=UID THREAD=ORDEREDSUBJECT THREAD=REFERENCES THREAD=REFS ANNOTATEMORE ANNOTATE-EXPERIMENT-1 METADATA LIST-EXTENDED LIST-STATUS LIST-MYRIGHTS LIST-METADATA WITHIN QRESYNC SCAN XLIST XMOVE MOVE SPECIAL-USE CREATE-SPECIAL-USE DIGEST=SHA1 X-REPLICATION URLAUTH URLAUTH=BINARY LOGINDISABLED COMPRESS=DEFLATE X-QUOTA=STORAGE X-QUOTA=MESSAGE X-QUOTA=X-ANNOTATION-STORAGE X-QUOTA=X-NUM-FOLDERS IDLE] User logged in SESSIONID=<1702540405-12412-1525107776-1-3475325977581003684>
C: 3 create user.cassandane
S: 3 OK Completed
C: 4 setacl user.cassandane admin lrswipkxtecdan
S: 4 OK Completed
C: 5 setacl user.cassandane cassandane lrswipkxtecdn
S: 5 OK Completed
C: 6 setacl user.cassandane anyone p
S: 6 OK Completed
A: is_open test
A: is_open test received timeout, still open
C: 7 logout
S: * BYE LOGOUT received
S: 7 OK Completed
A: Release socket, fileno=16
=====> Instance[1109] started main instance for test test_supports_event: cyrus version 3.0.6-1.fc29 Fedora
=====> Cyrus::TestCase[572] Calling test function
******** REDIRECT 301 to http://127.0.0.1:19170/dav/calendars
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< PROPFIND http://127.0.0.1:19170/.well-known/caldav HTTP/1.1
<D:propfind xmlns:CY='http://cyrusimap.org/ns/' xmlns:UF='http://cyrusimap.org/ns/userflag/' xmlns:D='DAV:' xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:A='http://apple.com/ns/ical/' xmlns:C='urn:ietf:params:xml:ns:caldav'><D:prop><D:current-user-principal/></D:prop></D:propfind>
>>>>>>>> HTTP/1.1 207 Multi-Status
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:CY="http://cyrusimap.org/ns/" xmlns:UF="http://cyrusimap.org/ns/userflag/" xmlns:D="DAV:" xmlns:SF="http://cyrusimap.org/ns/sysflag/" xmlns:A="http://apple.com/ns/ical/" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:response>
    <D:href>/dav/calendars</D:href>
    <D:propstat>
      <D:prop>
        <D:current-user-principal>
          <D:href>/dav/principals/user/cassandane/</D:href>
        </D:current-user-principal>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
========
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< PROPFIND http://127.0.0.1:19170/dav/principals/user/cassandane HTTP/1.1
<D:propfind xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:A='http://apple.com/ns/ical/' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:UF='http://cyrusimap.org/ns/userflag/' xmlns:CY='http://cyrusimap.org/ns/' xmlns:D='DAV:'><D:prop><C:calendar-home-set/></D:prop></D:propfind>
>>>>>>>> HTTP/1.1 207 Multi-Status
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:SF="http://cyrusimap.org/ns/sysflag/" xmlns:A="http://apple.com/ns/ical/" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:UF="http://cyrusimap.org/ns/userflag/" xmlns:CY="http://cyrusimap.org/ns/" xmlns:D="DAV:">
  <D:response>
    <D:href>/dav/principals/user/cassandane</D:href>
    <D:propstat>
      <D:prop>
        <C:calendar-home-set>
          <D:href>/dav/calendars/user/cassandane/</D:href>
        </C:calendar-home-set>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
========
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< PROPFIND http://127.0.0.1:19170/dav/principals/user/cassandane HTTP/1.1
<D:propfind xmlns:D='DAV:' xmlns:CY='http://cyrusimap.org/ns/' xmlns:UF='http://cyrusimap.org/ns/userflag/' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:A='http://apple.com/ns/ical/'><D:prop><D:displayname/><C:calendar-user-address-set/></D:prop></D:propfind>
>>>>>>>> HTTP/1.1 207 Multi-Status
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:CY="http://cyrusimap.org/ns/" xmlns:UF="http://cyrusimap.org/ns/userflag/" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:SF="http://cyrusimap.org/ns/sysflag/" xmlns:A="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/dav/principals/user/cassandane</D:href>
    <D:propstat>
      <D:prop>
        <D:displayname>cassandane</D:displayname>
        <C:calendar-user-address-set>
          <D:href>mailto:cassandane@defdomain</D:href>
        </C:calendar-user-address-set>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
========
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< PROPPATCH http://127.0.0.1:19170/dav/calendars/user/cassandane HTTP/1.1
<D:propertyupdate xmlns:A='http://apple.com/ns/ical/' xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:UF='http://cyrusimap.org/ns/userflag/' xmlns:CY='http://cyrusimap.org/ns/' xmlns:D='DAV:'><D:set><D:prop><D:displayname>Test User</D:displayname><C:calendar-user-address-set>mailto:cassandane@example.com</C:calendar-user-address-set></D:prop></D:set></D:propertyupdate>
>>>>>>>> HTTP/1.1 207 Multi-Status
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:A="http://apple.com/ns/ical/" xmlns:SF="http://cyrusimap.org/ns/sysflag/" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:UF="http://cyrusimap.org/ns/userflag/" xmlns:CY="http://cyrusimap.org/ns/" xmlns:D="DAV:">
  <D:response>
    <D:href>/dav/calendars/user/cassandane/</D:href>
    <D:propstat>
      <D:prop>
        <D:displayname/>
        <C:calendar-user-address-set/>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
========
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< MKCALENDAR http://127.0.0.1:19170/dav/calendars/user/cassandane/5458EEF4-4C98-11E8-937B-3647095EFCB2/ HTTP/1.1
<C:mkcalendar xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:A='http://apple.com/ns/ical/' xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:D='DAV:' xmlns:CY='http://cyrusimap.org/ns/' xmlns:UF='http://cyrusimap.org/ns/userflag/'><D:set><D:prop><D:displayname>foo</D:displayname></D:prop></D:set></C:mkcalendar>
>>>>>>>> HTTP/1.1 201 Created
========
=====> Instance[1871] authdaemon connection: cassandane pass http 
<<<<<<<< PROPFIND http://127.0.0.1:19170/dav/calendars/user/cassandane HTTP/1.1
<D:propfind xmlns:D='DAV:' xmlns:UF='http://cyrusimap.org/ns/userflag/' xmlns:CY='http://cyrusimap.org/ns/' xmlns:C='urn:ietf:params:xml:ns:caldav' xmlns:SF='http://cyrusimap.org/ns/sysflag/' xmlns:A='http://apple.com/ns/ical/'><D:prop><D:resourcetype/><D:current-user-privilege-set/><A:calendar-color/><C:calendar-timezone/><D:displayname/><D:acl/><D:supported-report-set/><D:sync-token/><A:calendar-order/><C:supported-calendar-data/></D:prop></D:propfind>
>>>>>>>> HTTP/1.1 207 Multi-Status
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:UF="http://cyrusimap.org/ns/userflag/" xmlns:CY="http://cyrusimap.org/ns/" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:SF="http://cyrusimap.org/ns/sysflag/" xmlns:A="http://apple.com/ns/ical/">
  <D:response>
    <D:href>/dav/calendars/user/cassandane/</D:href>
    <D:propstat>
      <D:prop>
        <D:resourcetype>
          <D:collection/>
        </D:resourcetype>
        <D:current-user-privilege-set>
          <D:privilege>
            <D:all/>
          </D:privilege>
          <D:privilege>
            <D:read/>
          </D:privilege>
          <D:privilege>
            <C:read-free-busy/>
          </D:privilege>
          <D:privilege>
            <D:write/>
          </D:privilege>
          <D:privilege>
            <D:write-content/>
          </D:privilege>
          <D:privilege>
            <D:write-properties/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-collection/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-resource/>
          </D:privilege>
          <D:privilege>
            <D:bind/>
          </D:privilege>
          <D:privilege>
            <CY:make-collection/>
          </D:privilege>
          <D:privilege>
            <CY:add-resource/>
          </D:privilege>
          <D:privilege>
            <D:unbind/>
          </D:privilege>
          <D:privilege>
            <CY:remove-collection/>
          </D:privilege>
          <D:privilege>
            <CY:remove-resource/>
          </D:privilege>
          <D:privilege>
            <CY:admin/>
          </D:privilege>
        </D:current-user-privilege-set>
        <D:displayname><![CDATA[Test User]]></D:displayname>
        <D:acl>
          <D:ace>
            <D:principal>
              <D:self/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:href>/dav/principals/user/admin/</D:href>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:all/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <C:read-free-busy/>
              </D:privilege>
            </D:grant>
          </D:ace>
        </D:acl>
        <D:supported-report-set>
          <D:supported-report>
            <D:report>
              <D:expand-property/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:acl-principal-prop-set/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:sync-collection/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-query/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-multiget/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:free-busy-query/>
            </D:report>
          </D:supported-report>
        </D:supported-report-set>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <A:calendar-color/>
        <C:calendar-timezone/>
        <D:sync-token/>
        <A:calendar-order/>
        <C:supported-calendar-data/>
      </D:prop>
      <D:status>HTTP/1.1 404 Not Found</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/dav/calendars/user/cassandane/5458EEF4-4C98-11E8-937B-3647095EFCB2/</D:href>
    <D:propstat>
      <D:prop>
        <D:resourcetype>
          <D:collection/>
          <C:calendar/>
        </D:resourcetype>
        <D:current-user-privilege-set>
          <D:privilege>
            <D:all/>
          </D:privilege>
          <D:privilege>
            <D:read/>
          </D:privilege>
          <D:privilege>
            <C:read-free-busy/>
          </D:privilege>
          <D:privilege>
            <D:write/>
          </D:privilege>
          <D:privilege>
            <D:write-content/>
          </D:privilege>
          <D:privilege>
            <D:write-properties/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-collection/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-resource/>
          </D:privilege>
          <D:privilege>
            <D:bind/>
          </D:privilege>
          <D:privilege>
            <CY:make-collection/>
          </D:privilege>
          <D:privilege>
            <CY:add-resource/>
          </D:privilege>
          <D:privilege>
            <D:unbind/>
          </D:privilege>
          <D:privilege>
            <CY:remove-collection/>
          </D:privilege>
          <D:privilege>
            <CY:remove-resource/>
          </D:privilege>
          <D:privilege>
            <CY:admin/>
          </D:privilege>
        </D:current-user-privilege-set>
        <D:displayname><![CDATA[foo]]></D:displayname>
        <D:acl>
          <D:ace>
            <D:principal>
              <D:self/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:href>/dav/principals/user/admin/</D:href>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:all/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <C:read-free-busy/>
              </D:privilege>
            </D:grant>
          </D:ace>
        </D:acl>
        <D:supported-report-set>
          <D:supported-report>
            <D:report>
              <D:expand-property/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:acl-principal-prop-set/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:sync-collection/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-query/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-multiget/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:free-busy-query/>
            </D:report>
          </D:supported-report>
        </D:supported-report-set>
        <D:sync-token>data:,1525107777-2</D:sync-token>
        <C:supported-calendar-data>
          <C:calendar-data content-type="text/calendar" version="2.0"/>
          <C:calendar-data content-type="application/calendar+xml"/>
          <C:calendar-data content-type="application/calendar+json"/>
        </C:supported-calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <A:calendar-color/>
        <C:calendar-timezone/>
        <A:calendar-order/>
      </D:prop>
      <D:status>HTTP/1.1 404 Not Found</D:status>
    </D:propstat>
  </D:response>
  <D:response>
    <D:href>/dav/calendars/user/cassandane/Default/</D:href>
    <D:propstat>
      <D:prop>
        <D:resourcetype>
          <D:collection/>
          <C:calendar/>
        </D:resourcetype>
        <D:current-user-privilege-set>
          <D:privilege>
            <D:all/>
          </D:privilege>
          <D:privilege>
            <D:read/>
          </D:privilege>
          <D:privilege>
            <C:read-free-busy/>
          </D:privilege>
          <D:privilege>
            <D:write/>
          </D:privilege>
          <D:privilege>
            <D:write-content/>
          </D:privilege>
          <D:privilege>
            <D:write-properties/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-collection/>
          </D:privilege>
          <D:privilege>
            <CY:write-properties-resource/>
          </D:privilege>
          <D:privilege>
            <D:bind/>
          </D:privilege>
          <D:privilege>
            <CY:make-collection/>
          </D:privilege>
          <D:privilege>
            <CY:add-resource/>
          </D:privilege>
          <D:privilege>
            <D:unbind/>
          </D:privilege>
          <D:privilege>
            <CY:remove-collection/>
          </D:privilege>
          <D:privilege>
            <CY:remove-resource/>
          </D:privilege>
          <D:privilege>
            <CY:admin/>
          </D:privilege>
        </D:current-user-privilege-set>
        <D:displayname><![CDATA[personal]]></D:displayname>
        <D:acl>
          <D:ace>
            <D:principal>
              <D:self/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:href>/dav/principals/user/admin/</D:href>
            </D:principal>
            <D:grant>
              <D:privilege>
                <D:all/>
              </D:privilege>
            </D:grant>
          </D:ace>
          <D:ace>
            <D:principal>
              <D:all/>
            </D:principal>
            <D:grant>
              <D:privilege>
                <C:read-free-busy/>
              </D:privilege>
            </D:grant>
          </D:ace>
        </D:acl>
        <D:supported-report-set>
          <D:supported-report>
            <D:report>
              <D:expand-property/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:acl-principal-prop-set/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <D:sync-collection/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-query/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:calendar-multiget/>
            </D:report>
          </D:supported-report>
          <D:supported-report>
            <D:report>
              <C:free-busy-query/>
            </D:report>
          </D:supported-report>
        </D:supported-report-set>
        <D:sync-token>data:,1525107777-2</D:sync-token>
        <C:supported-calendar-data>
          <C:calendar-data content-type="text/calendar" version="2.0"/>
          <C:calendar-data content-type="application/calendar+xml"/>
          <C:calendar-data content-type="application/calendar+json"/>
        </C:supported-calendar-data>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
    <D:propstat>
      <D:prop>
        <A:calendar-color/>
        <C:calendar-timezone/>
        <A:calendar-order/>
      </D:prop>
      <D:status>HTTP/1.1 404 Not Found</D:status>
    </D:propstat>
  </D:response>
</D:multistatus>
========
=====> Cyrus::TestCase[679] Beginning tear_down
=====> Instance[1316] stop
=====> Instance[1278] _stop_pid: sending signal 15 to 12375
=====> Util::Wait[75] Waited 0.010057 sec for unknown condition
=====> Instance[1060] killing smtpd 12325
2018/04/30-12:02:57 Server closing!
=====> Instance[948] killing saslauthd 12339
Warning: unable to close filehandle $oldout properly: Bad file descriptor at /usr/share/perl5/vendor_perl/Net/Server/PreForkSimple.pm line 214.
Warning: unable to close filehandle $olderr properly: Bad file descriptor at /usr/share/perl5/vendor_perl/Net/Server/PreForkSimple.pm line 214.
Warning: unable to close filehandle $oldout properly: Bad file descriptor at /usr/lib64/perl5/IO/Select.pm line 120.
Warning: unable to close filehandle $olderr properly: Bad file descriptor at /usr/lib64/perl5/IO/Select.pm line 120.
Warning: unable to close filehandle $oldout properly: Bad file descriptor at Cassandane/Instance.pm line 942.
Warning: unable to close filehandle $olderr properly: Bad file descriptor at Cassandane/Instance.pm line 942.
=====> Instance[1060] killing smtpd 12325
=====> Instance[975] killing notifyd 12341
=====> Instance[1060] killing smtpd 12325
=====> Instance[948] killing saslauthd 12339
=====> Cyrus::TestCase[724] ---------- END test_supports_event ----------
=====> Daemon[385] checking for stray processes on ports: 19169 19170 19171
Test was not successful.
```

**Comment by elliefm** [comment] 2018-05-01 03:38
I went looking into this a couple of weeks ago and couldn't for the life of me work out what had changed, and then I guess I got used to it failing and stopped seeing it.  I thought it must've been a dependency change (because I started seeing it around the time I updated some dependencies) but it didn't seem to be the case, but that's as far as I got at the time.

It's probably going to take a tedious slog through bisect, at least if I tackle this.

@ksmurchison, @rsto, any hunches or ideas what this might be in relation to?  If not, I'll spend some time bisecting the 3.0 branch and see where it shows up.

**Comment by ksmurchison** [comment] 2018-05-01 04:02
I will look into it

**Comment by ksmurchison** [comment] 2018-05-01 15:33
OK.  I found the issue.  The _can_event call in CalDAVTalk is checking for application/event+json (JScalendar) as a supported mediatype in the supported-calendar-data property.  This mediatype isn't returned in 3.0.6.

I don't think CalDAVTalk should be checking for this new/special type.  It should be checking for text/calendar which is the default type for CalDAV.

**Comment by jasontibbitts** [comment] 2018-05-01 18:58
I've disabled the test in the Fedora packaging.  I don't know if this can be worked around in Cassandane or if it will need an update to Net::CalDAVTalk.

In any case, I did send a bug report to the CPAN RT instance referencing this ticket, but it's still grinding through the mail system.  I have a feeling you folks have better access to the Net::CalDAVTalk author than I do.

**Comment by ksmurchison** [comment] 2018-05-02 01:01
Actualy, if this test is truly designed to check for support of JSevent, then it should be made conditional on Cyrus 3.1

**Comment by elliefm** [comment] 2018-05-02 04:27
I guess this is the question isn't it, what is this test trying to actually achieve?

@brong added it back in 2016 (https://github.com/cyrusimap/cassandane/commit/2b990e215bf75bbd70eda3b28a4e1c25fe302120) so I guess it's _supposed_ to pass in 3.0.x

**Comment by elliefm** [comment] 2018-05-02 04:31
But then, 3.0.x was expected to contain JMAP back then, so 🤷‍♀️

**Comment by elliefm** [comment] 2018-05-02 04:49
Confirmed with bisect that the removal of JMAP (a7b6bc23ba5ef4b5fe81ba514f242f2dbff0d464) is what caused it to start failing this test

**Comment by ksmurchison** [comment] 2018-05-07 18:42
Resolved by https://github.com/cyrusimap/cassandane/commit/c32d0e5dbb66de279334a26fe853f146b9e0647a

**Closed by ksmurchison** 2018-05-07 18:42 UTC
