### ISSUE TITLE
Makefile.am: add lib/util.h to include_HEADERS

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1898] opened 2017-04-09 13:08 UTC
`make install` installs util/strarray.h , which includes lib/util.h, so lib/util.h must also be installed, but is not (as it appears under noinst_HEADERS).

Otherwise strarray.h cannot be used ouf of the source tree.

**Comment by ksmurchison** [comment] 2017-09-22 11:55
Duplicate of #2079

**Closed by ksmurchison** 2017-09-22 11:55 UTC
Labels: duplicate
